/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import { ServiceClientOptions } from "@azure/ms-rest-js";
import * as msRest from "@azure/ms-rest-js";


/**
 * @interface
 * An interface representing ProblemDetails.
 */
export interface ProblemDetails {
  /**
   * @member {string} [type]
   */
  type?: string;
  /**
   * @member {string} [title]
   */
  title?: string;
  /**
   * @member {number} [status]
   */
  status?: number;
  /**
   * @member {string} [detail]
   */
  detail?: string;
  /**
   * @member {string} [instance]
   */
  instance?: string;
  /**
   * @member {{ [propertyName: string]: any }} [extensions]
   */
  extensions?: { [propertyName: string]: any };
}

/**
 * @interface
 * An interface representing AccessToken.
 * An AccessToken used for authentication via the SDK
 *
 */
export interface AccessToken {
  /**
   * @member {string} id The public Id of the AccessToken
   */
  id: string;
  /**
   * @member {string} domain The Domain of the Catalytic team with which these
   * AccessToken are associated
   */
  domain: string;
  /**
   * @member {string} [name] The name associated with the AccessToken
   */
  name?: string;
  /**
   * @member {Type} [type] Possible values include: 'user', 'actionWorker'
   */
  type?: Type;
  /**
   * @member {string} [token] The serialized AccessToken Token
   */
  token?: string;
  /**
   * @member {string} [secret] The confidential Secret of the AccessToken
   */
  secret?: string;
  /**
   * @member {string} [environment] The environment of the Catalytic team
   * associated with the AccessToken
   */
  environment?: string;
  /**
   * @member {string} [owner] The email address of the user who these
   * AccessToken belong to
   */
  owner?: string;
}

/**
 * @interface
 * An interface representing PagingOptions.
 * Properties required for executing a search request
 *
 */
export interface PagingOptions {
  /**
   * @member {number} [size] The page size of search results
   */
  size?: number;
  /**
   * @member {string} [pageToken] A token used to retrieve the next page of
   * results
   */
  pageToken?: string;
  /**
   * @member {boolean} [getAllResults] Indicates whether all results should be
   * retrieved
   */
  getAllResults?: boolean;
}

/**
 * @interface
 * An interface representing AccessTokensPage.
 * Represents a page of AccessTokens
 *
 */
export interface AccessTokensPage {
  /**
   * @member {AccessToken[]} [accessTokens] The Collection of AccessTokens in
   * the page
   */
  accessTokens?: AccessToken[];
  /**
   * @member {PagingOptions} [nextPageOptions]
   */
  nextPageOptions?: PagingOptions;
  /**
   * @member {string} [nextPageToken]
   */
  nextPageToken?: string;
  /**
   * @member {number} [count]
   */
  count?: number;
}

/**
 * @interface
 * An interface representing AccessTokenCreationRequest.
 * Represents a request to generate new AccessToken for authentication into a
 * Catalytic team
 *
 */
export interface AccessTokenCreationRequest {
  /**
   * @member {string} domain Catalytic team domain to authenticate in to (ex:
   * "myteam.pushbot.com")
   */
  domain: string;
  /**
   * @member {string} [name] Optional Name to assign to AccessToken; visible in
   * Catalytic UI
   */
  name?: string;
}

/**
 * @interface
 * An interface representing AccessTokenCreationWithEmailAndPasswordRequest.
 * Represents a request to create and approve new AccessToken for
 * authentication into a Catalytic team
 * with passed username and password
 *
 */
export interface AccessTokenCreationWithEmailAndPasswordRequest {
  /**
   * @member {string} email Optional email address of the Catalytic user for
   * whom the AccessToken should be created
   */
  email: string;
  /**
   * @member {string} password Optional password of the Catalytic user for whom
   * the AccessToken should be created
   */
  password: string;
  /**
   * @member {string} domain Catalytic team domain to authenticate in to (ex:
   * "myteam.pushbot.com")
   */
  domain: string;
  /**
   * @member {string} [name] Optional Name to assign to AccessToken; visible in
   * Catalytic UI
   */
  name?: string;
}

/**
 * @interface
 * An interface representing WaitForAccessTokenApprovalRequest.
 * A request to activate AccessToken
 *
 */
export interface WaitForAccessTokenApprovalRequest {
  /**
   * @member {string} token AccessToken string
   */
  token: string;
  /**
   * @member {number} [waitTimeMillis] Optional timeout to wait for AccessToken
   * to be approved via UI (milliseconds)
   * Defaults to 300000ms (5 minutes)
   */
  waitTimeMillis?: number;
}

/**
 * @interface
 * An interface representing FieldRestrictions.
 * Contains validation rules for field values
 *
 */
export interface FieldRestrictions {
  /**
   * @member {string[]} [choices] A set of valid choices for this field. If
   * set, FieldType must be
   * SingleChoice or MultipleChoice
   */
  choices?: string[];
  /**
   * @member {boolean} [valueRequired] Indicates whether null or empty values
   * will be rejected
   */
  valueRequired?: boolean;
}

/**
 * @interface
 * An interface representing DataTableColumn.
 */
export interface DataTableColumn {
  /**
   * @member {string} [name]
   */
  name?: string;
  /**
   * @member {Type1} [type] Possible values include: 'undefined', 'text',
   * 'integer', 'decimal', 'date', 'dateTime', 'json', 'bool', 'singleChoice',
   * 'multipleChoice', 'instructions', 'file', 'table', 'workflow', 'instance',
   * 'user', 'password'
   */
  type?: Type1;
  /**
   * @member {string} [referenceName]
   */
  referenceName?: string;
  /**
   * @member {FieldRestrictions} [restrictions]
   */
  restrictions?: FieldRestrictions;
}

/**
 * @interface
 * An interface representing DataTable.
 */
export interface DataTable {
  /**
   * @member {string} id The unique ID of the Data Table
   */
  id: string;
  /**
   * @member {string} [dataTableId] Alias for `Id`
   */
  dataTableId?: string;
  /**
   * @member {string} [referenceName] Gets a unique reference name for this
   * Data Table
   */
  referenceName?: string;
  /**
   * @member {string} name The descriptive name of the Data Table
   */
  name: string;
  /**
   * @member {string} teamName The name of the team in which the Data Table is
   * defined
   */
  teamName: string;
  /**
   * @member {string} [description] A description of what kind of data is
   * stored in the Table
   */
  description?: string;
  /**
   * @member {DataTableColumn[]} [columns] The ordered names of the columns in
   * this Data Table
   */
  columns?: DataTableColumn[];
  /**
   * @member {boolean} [isArchived] Whether or not this table is archived and
   * excluded from default searches
   */
  isArchived?: boolean;
  /**
   * @member {Type2} [type] Possible values include: 'imported', 'master',
   * 'application', 'instance', 'batch'
   */
  type?: Type2;
  /**
   * @member {Visibility} [visibility] Possible values include: 'open',
   * 'restricted'
   */
  visibility?: Visibility;
  /**
   * @member {string[]} [visibleToUsers] The users who can find and modify this
   * Data Table
   */
  visibleToUsers?: string[];
  /**
   * @member {number} [rowLimit] The maximum number of rows in this Data Table
   */
  rowLimit?: number;
  /**
   * @member {number} [columnLimit] The maximum number of columns in this Data
   * Table
   */
  columnLimit?: number;
  /**
   * @member {number} [cellLimit] The maximum number of cells in this Data
   * Table
   */
  cellLimit?: number;
}

/**
 * @interface
 * An interface representing DataTablesPage.
 * A page of DataTables returned from a FindAync request
 *
 */
export interface DataTablesPage {
  /**
   * @member {DataTable[]} [dataTables] The list of DataTables
   */
  dataTables?: DataTable[];
  /**
   * @member {PagingOptions} [nextPageOptions]
   */
  nextPageOptions?: PagingOptions;
  /**
   * @member {string} [nextPageToken]
   */
  nextPageToken?: string;
  /**
   * @member {number} [count]
   */
  count?: number;
}

/**
 * @interface
 * An interface representing FileMetadata.
 */
export interface FileMetadata {
  /**
   * @member {string} [id] The unique ID of the File in Catalytic
   */
  id?: string;
  /**
   * @member {string} [name] The name of the File
   */
  name?: string;
  /**
   * @member {string} [teamName] The name of the Catalytic team with which the
   * File is associated
   */
  teamName?: string;
  /**
   * @member {string} [contentType] The content-type of the File
   */
  contentType?: string;
  /**
   * @member {number} [sizeInBytes] The size of the File, in bytes
   */
  sizeInBytes?: number;
  /**
   * @member {string} [displaySize] The human-readable size of the File
   */
  displaySize?: string;
  /**
   * @member {boolean} [isPublic] Boolean indicating whether the File can be
   * downloaded by unauthenticated users
   */
  isPublic?: boolean;
  /**
   * @member {string} [md5Hash] The MD5 hash of the File
   */
  md5Hash?: string;
  /**
   * @member {string} [referenceName] The stringified ID of the File, used for
   * reference in a !:FilesPage
   */
  referenceName?: string;
}

/**
 * @interface
 * An interface representing FileMetadataPage.
 */
export interface FileMetadataPage {
  /**
   * @member {FileMetadata[]} [files] A Collection of items with Dictionaries
   * keyed by both ID and ReferenceName
   */
  files?: FileMetadata[];
  /**
   * @member {PagingOptions} [nextPageOptions]
   */
  nextPageOptions?: PagingOptions;
  /**
   * @member {string} [nextPageToken]
   */
  nextPageToken?: string;
  /**
   * @member {number} [count]
   */
  count?: number;
}

/**
 * @interface
 * An interface representing Field.
 * Represents a named and typed variable within a Workflow or Instance
 *
 */
export interface Field {
  /**
   * @member {string} [id] The unique ID of the field
   */
  id?: string;
  /**
   * @member {string} [name] The descriptive name of the Field
   */
  name?: string;
  /**
   * @member {string} [referenceName] A unique name (within the scope of the
   * Workflow or Instance) that
   * can be used to reference the value of this field in
   * a template or operation.
   */
  referenceName?: string;
  /**
   * @member {string} [description] A description of this field. This can be
   * used as instructions
   * for users filling out this field in a form
   */
  description?: string;
  /**
   * @member {string} [example] An example of possible values for this field.
   */
  example?: string;
  /**
   * @member {number} [position] The visual position of this field relative
   * others in the same scope
   */
  position?: number;
  /**
   * @member {FieldRestrictions} [restrictions]
   */
  restrictions?: FieldRestrictions;
  /**
   * @member {FieldType} [fieldType] Possible values include: 'undefined',
   * 'text', 'integer', 'decimal', 'date', 'dateTime', 'json', 'bool',
   * 'singleChoice', 'multipleChoice', 'instructions', 'file', 'table',
   * 'workflow', 'instance', 'user', 'password'
   */
  fieldType?: FieldType;
  /**
   * @member {string} [value] The value of this field, serialized as a string
   */
  value?: string;
  /**
   * @member {string} [templateValue] The template expression that will become
   * the field value
   * once it is evaluated
   */
  templateValue?: string;
  /**
   * @member {string} [defaultValue] The optional default value of this field,
   * serialized as a string. The
   * serialization format depends on the type of field.
   */
  defaultValue?: string;
}

/**
 * @interface
 * An interface representing InstanceStep.
 * Represents a single Step of an Instance
 *
 */
export interface InstanceStep {
  /**
   * @member {string} id Unique ID of this Task
   */
  id: string;
  /**
   * @member {string} instanceId Unique ID of this Instance to which this Step
   * belongs
   */
  instanceId: string;
  /**
   * @member {string} workflowId Unique ID of the Workflow to which this Step
   * belongs
   */
  workflowId: string;
  /**
   * @member {string} name Display name of this Task
   */
  name: string;
  /**
   * @member {string} teamName The name of the Catalytic team in which this
   * Task exists
   */
  teamName: string;
  /**
   * @member {number} [position] The position of this Task amongst the other
   * Tasks in the Instance
   */
  position?: number;
  /**
   * @member {string} [description] A description or instructions of the Task
   */
  description?: string;
  /**
   * @member {Status} [status] Possible values include: 'pending', 'active',
   * 'completed', 'cancelled', 'snoozed', 'skipped', 'error'
   */
  status?: Status;
  /**
   * @member {string} [assignedTo] The email of the user (if any) that this
   * InstanceStep is assigned to
   */
  assignedTo?: string;
  /**
   * @member {string} [actionTypeId] The ID of this action type of this step
   */
  actionTypeId?: string;
  /**
   * @member {boolean} [isAutomated] Indicates whether or not this step is an
   * automated action that will be completed without manual intervention.
   */
  isAutomated?: boolean;
  /**
   * @member {boolean} [isManual] Indicates whether or not this step is manual,
   * to be completed by a person.
   * This is a convinience property that gets/sets the inverse of
   * Catalytic.Sdk.Entities.InstanceStep.IsAutomated.
   */
  isManual?: boolean;
  /**
   * @member {Date} [startDate] The start date of the step, or null if the step
   * has not started
   */
  startDate?: Date;
  /**
   * @member {Date} [endDate] The end date of the step, or null if the step has
   * not started
   */
  endDate?: Date;
  /**
   * @member {Field[]} [outputFields] A collection of the required and optional
   * output fields
   * that can be set by this InstanceStep when completing it.
   */
  outputFields?: Field[];
}

/**
 * @interface
 * An interface representing Instance.
 * Represents an Instance of a Workflow
 *
 */
export interface Instance {
  /**
   * @member {string} id The unique ID of the Instance
   */
  id: string;
  /**
   * @member {string} workflowId The unique ID of the Workflow this Instance
   * was started from
   */
  workflowId: string;
  /**
   * @member {string} [name] The descriptive name of the Instance
   */
  name?: string;
  /**
   * @member {string} teamName The name of the Catalytic team in which this
   * Instance was started
   */
  teamName: string;
  /**
   * @member {string} [description] A description of the Instance
   */
  description?: string;
  /**
   * @member {string} [category] A descriptive grouping for the Instance
   */
  category?: string;
  /**
   * @member {string} [owner] The email address of the user who owns this
   * Instance
   */
  owner?: string;
  /**
   * @member {string} [createdBy] The email address of the user who created
   * this Instance
   */
  createdBy?: string;
  /**
   * @member {InstanceStep[]} [steps] A collection of the Tasks belonging to
   * this Instance
   */
  steps?: InstanceStep[];
  /**
   * @member {Field[]} [fields] A collection of the Fields belonging to this
   * Instance
   */
  fields?: Field[];
  /**
   * @member {Status1} [status] Possible values include: 'running',
   * 'completed', 'cancelled'
   */
  status?: Status1;
  /**
   * @member {Date} [startDate] The start date of the instance
   */
  startDate?: Date;
  /**
   * @member {Date} [endDate] The end date of the instance, or null if the step
   * has not started
   */
  endDate?: Date;
  /**
   * @member {FieldVisibility} [fieldVisibility] Possible values include:
   * 'public', 'internal', 'confidential', 'highlyConfidential'
   */
  fieldVisibility?: FieldVisibility;
  /**
   * @member {Visibility1} [visibility] Possible values include: 'open',
   * 'restricted'
   */
  visibility?: Visibility1;
  /**
   * @member {string[]} [visibleToUsers] The users who can find and interact
   * with this Instance
   */
  visibleToUsers?: string[];
}

/**
 * @interface
 * An interface representing InstancesPage.
 * A page of Instances returned from a FindAync request
 *
 */
export interface InstancesPage {
  /**
   * @member {Instance[]} [instances] The list of Instances
   */
  instances?: Instance[];
  /**
   * @member {PagingOptions} [nextPageOptions]
   */
  nextPageOptions?: PagingOptions;
  /**
   * @member {string} [nextPageToken]
   */
  nextPageToken?: string;
  /**
   * @member {number} [count]
   */
  count?: number;
}

/**
 * @interface
 * An interface representing FieldUpdateRequest.
 * Request to update the value of a field
 *
 */
export interface FieldUpdateRequest {
  /**
   * @member {string} [name] The name of the field
   */
  name?: string;
  /**
   * @member {string} [referenceName] The reference name of the field
   */
  referenceName?: string;
  /**
   * @member {string} [value] The string-serialized value of the field
   */
  value?: string;
}

/**
 * @interface
 * An interface representing StartInstanceRequest.
 */
export interface StartInstanceRequest {
  /**
   * @member {string} [workflowId] ID of the Workflow to start
   */
  workflowId?: string;
  /**
   * @member {string} [name] Optional name for the instance
   */
  name?: string;
  /**
   * @member {string} [description] Optional description for the instance
   */
  description?: string;
  /**
   * @member {FieldUpdateRequest[]} [inputFields] A collection of the required
   * and optional input fields
   * that can be passed to this Workflow when starting it.
   */
  inputFields?: FieldUpdateRequest[];
}

/**
 * @interface
 * An interface representing InstanceStepsPage.
 * A page of Instance Steps returned from a FindAync request
 *
 */
export interface InstanceStepsPage {
  /**
   * @member {InstanceStep[]} [steps] The list of Steps
   */
  steps?: InstanceStep[];
  /**
   * @member {PagingOptions} [nextPageOptions]
   */
  nextPageOptions?: PagingOptions;
  /**
   * @member {string} [nextPageToken]
   */
  nextPageToken?: string;
  /**
   * @member {number} [count]
   */
  count?: number;
}

/**
 * @interface
 * An interface representing CompleteStepRequest.
 */
export interface CompleteStepRequest {
  /**
   * @member {string} [id] ID of the step to complete
   */
  id?: string;
  /**
   * @member {FieldUpdateRequest[]} [stepOutputFields] A collection of the
   * required and optional input fields
   * that can be passed to this Workflow when starting it.
   */
  stepOutputFields?: FieldUpdateRequest[];
}

/**
 * @interface
 * An interface representing ReassignStepRequest.
 */
export interface ReassignStepRequest {
  /**
   * @member {string} [id] ID of the step to reassign
   */
  id?: string;
  /**
   * @member {string} [assignTo] The email address of the user to reassign the
   * task to
   */
  assignTo?: string;
}

/**
 * @interface
 * An interface representing IntegrationConnection.
 */
export interface IntegrationConnection {
  /**
   * @member {string} [id] The unique Id of the Integration Connection
   */
  id?: string;
  /**
   * @member {string} [name] The display Name of the Integration Connection
   */
  name?: string;
  /**
   * @member {string} [referenceName] The unique Reference Name of the
   * Integration Connection
   */
  referenceName?: string;
  /**
   * @member {string} [integrationId] The Id of the Integration Definition with
   * which this Integration Connection was created
   */
  integrationId?: string;
  /**
   * @member {Date} [createdAt] The DateTime at which the Integration
   * Connection was created
   */
  createdAt?: Date;
}

/**
 * @interface
 * An interface representing Integration.
 */
export interface Integration {
  /**
   * @member {string} [id] The unique ID of the Integration
   */
  id?: string;
  /**
   * @member {string} [referenceName]
   */
  referenceName?: string;
  /**
   * @member {string} [name] The display Name of the Integration
   */
  name?: string;
  /**
   * @member {boolean} [isCustomIntegration] Boolean indicating whether this
   * Integration Defintion is custom to your Catalytic team.
   * Only custom Integrations can be updated using the SDK.
   */
  isCustomIntegration?: boolean;
  /**
   * @member {IntegrationConnection[]} [connections] The List of Integration
   * Connections using this Integration
   */
  connections?: IntegrationConnection[];
  /**
   * @member {Field[]} [connectionParams] The values required to create a new
   */
  connectionParams?: Field[];
}

/**
 * @interface
 * An interface representing IntegrationsPage.
 * A page of Integrations returned from a FindAync request
 *
 */
export interface IntegrationsPage {
  /**
   * @member {Integration[]} [integrations] The list of Integrations
   */
  integrations?: Integration[];
  /**
   * @member {PagingOptions} [nextPageOptions]
   */
  nextPageOptions?: PagingOptions;
  /**
   * @member {string} [nextPageToken]
   */
  nextPageToken?: string;
  /**
   * @member {number} [count]
   */
  count?: number;
}

/**
 * @interface
 * An interface representing IntegrationConfiguration.
 * Authentication configuration settings for the Integration Definition
 *
 */
export interface IntegrationConfiguration {
  /**
   * @member {string} clientId Client Id corresponding to the custom OAuth
   * application
   */
  clientId: string;
  /**
   * @member {string} clientSecret Client Secret corresponding to the custom
   * OAuth application
   */
  clientSecret: string;
  /**
   * @member {string} tokenPath Token Path corresponding to the custom OAuth
   * application
   */
  tokenPath: string;
  /**
   * @member {string} revokePath Token Revoke Path corresponding to the custom
   * OAuth application
   */
  revokePath: string;
  /**
   * @member {string} site The site corresponding to the custom OAuth
   * application
   */
  site: string;
  /**
   * @member {string} authorizeBaseUrl The Authorization base url corresponding
   * to the custom OAuth application
   */
  authorizeBaseUrl: string;
  /**
   * @member {string[]} [scopes] The scopes corresponding to the custom OAuth
   * application
   */
  scopes?: string[];
  /**
   * @member {boolean} [useBodyAuth] Whether to supply authorization
   * credentials in the body of the request
   */
  useBodyAuth?: boolean;
}

/**
 * @interface
 * An interface representing IntegrationCreationRequest.
 */
export interface IntegrationCreationRequest {
  /**
   * @member {string} name The display Name to apply to the  Integration
   */
  name: string;
  /**
   * @member {IntegrationConfiguration} config
   */
  config: IntegrationConfiguration;
}

/**
 * @interface
 * An interface representing IntegrationUpdateRequest.
 */
export interface IntegrationUpdateRequest {
  /**
   * @member {string} name The display Name to apply to the Integration
   * Definition
   */
  name: string;
  /**
   * @member {IntegrationConfiguration} config
   */
  config: IntegrationConfiguration;
}

/**
 * @interface
 * An interface representing IntegrationConnectionCreationRequest.
 * A request to create a new IntegrationConnection
 *
 */
export interface IntegrationConnectionCreationRequest {
  /**
   * @member {string} [integrationId] The Id of the Integration with which the
   * Connection will be created
   */
  integrationId?: string;
  /**
   * @member {string} [name] The display Name to apply to the new Integration
   * Connection
   */
  name?: string;
  /**
   * @member {FieldUpdateRequest[]} [connectionParams] Parameters used to
   * create an Integration Connection
   */
  connectionParams?: FieldUpdateRequest[];
}

/**
 * @interface
 * An interface representing User.
 * Represents a user on a Catalytic team
 *
 */
export interface User {
  /**
   * @member {string} id Unique ID for the user
   */
  id: string;
  /**
   * @member {string} [username] Unique username of user
   */
  username?: string;
  /**
   * @member {string} email The email address associated with this user
   */
  email: string;
  /**
   * @member {string} fullName The user's full name
   */
  fullName: string;
  /**
   * @member {string} teamName The name of this User's Catalytic team
   */
  teamName: string;
}

/**
 * @interface
 * An interface representing UsersPage.
 * A page of Users returned from a FindAsync request
 *
 */
export interface UsersPage {
  /**
   * @member {User[]} [users] The List of Users
   */
  users?: User[];
  /**
   * @member {PagingOptions} [nextPageOptions]
   */
  nextPageOptions?: PagingOptions;
  /**
   * @member {string} [nextPageToken]
   */
  nextPageToken?: string;
  /**
   * @member {number} [count]
   */
  count?: number;
}

/**
 * @interface
 * An interface representing GuidNullableRange.
 */
export interface GuidNullableRange {
  /**
   * @member {string} [lowerBoundInclusive]
   */
  lowerBoundInclusive?: string;
  /**
   * @member {string} [upperBoundInclusive]
   */
  upperBoundInclusive?: string;
}

/**
 * @interface
 * An interface representing GuidSearchExpression.
 */
export interface GuidSearchExpression {
  /**
   * @member {string} [isEqualTo]
   */
  isEqualTo?: string;
  /**
   * @member {GuidNullableRange} [between]
   */
  between?: GuidNullableRange;
  /**
   * @member {string} [contains]
   */
  contains?: string;
}

/**
 * @interface
 * An interface representing StringRange.
 */
export interface StringRange {
  /**
   * @member {string} [lowerBoundInclusive]
   */
  lowerBoundInclusive?: string;
  /**
   * @member {string} [upperBoundInclusive]
   */
  upperBoundInclusive?: string;
}

/**
 * @interface
 * An interface representing StringSearchExpression.
 */
export interface StringSearchExpression {
  /**
   * @member {string} [isEqualTo]
   */
  isEqualTo?: string;
  /**
   * @member {StringRange} [between]
   */
  between?: StringRange;
  /**
   * @member {string} [contains]
   */
  contains?: string;
}

/**
 * @interface
 * An interface representing BooleanNullableRange.
 */
export interface BooleanNullableRange {
  /**
   * @member {boolean} [lowerBoundInclusive]
   */
  lowerBoundInclusive?: boolean;
  /**
   * @member {boolean} [upperBoundInclusive]
   */
  upperBoundInclusive?: boolean;
}

/**
 * @interface
 * An interface representing BoolSearchExpression.
 */
export interface BoolSearchExpression {
  /**
   * @member {boolean} [isEqualTo]
   */
  isEqualTo?: boolean;
  /**
   * @member {BooleanNullableRange} [between]
   */
  between?: BooleanNullableRange;
  /**
   * @member {boolean} [contains]
   */
  contains?: boolean;
}

/**
 * @interface
 * An interface representing DateTimeOffsetNullableRange.
 */
export interface DateTimeOffsetNullableRange {
  /**
   * @member {Date} [lowerBoundInclusive]
   */
  lowerBoundInclusive?: Date;
  /**
   * @member {Date} [upperBoundInclusive]
   */
  upperBoundInclusive?: Date;
}

/**
 * @interface
 * An interface representing DateTimeSearchExpression.
 */
export interface DateTimeSearchExpression {
  /**
   * @member {Date} [isEqualTo]
   */
  isEqualTo?: Date;
  /**
   * @member {DateTimeOffsetNullableRange} [between]
   */
  between?: DateTimeOffsetNullableRange;
  /**
   * @member {Date} [contains]
   */
  contains?: Date;
}

/**
 * @interface
 * An interface representing UserSearchClause.
 */
export interface UserSearchClause {
  /**
   * @member {UserSearchClause[]} [and]
   */
  and?: UserSearchClause[];
  /**
   * @member {UserSearchClause[]} [or]
   */
  or?: UserSearchClause[];
  /**
   * @member {GuidSearchExpression} [id]
   */
  id?: GuidSearchExpression;
  /**
   * @member {StringSearchExpression} [email]
   */
  email?: StringSearchExpression;
  /**
   * @member {StringSearchExpression} [fullName]
   */
  fullName?: StringSearchExpression;
  /**
   * @member {BoolSearchExpression} [isTeamAdmin]
   */
  isTeamAdmin?: BoolSearchExpression;
  /**
   * @member {BoolSearchExpression} [isDeactivated]
   */
  isDeactivated?: BoolSearchExpression;
  /**
   * @member {BoolSearchExpression} [isLockedOut]
   */
  isLockedOut?: BoolSearchExpression;
  /**
   * @member {DateTimeSearchExpression} [createdDate]
   */
  createdDate?: DateTimeSearchExpression;
}

/**
 * @interface
 * An interface representing Workflow.
 * A Workflow is an automation on the Catalytic platform. It is a template
 * of the process you want to run each time your Workflow is started.
 *
 */
export interface Workflow {
  /**
   * @member {string} id The unique ID of the Workflow
   */
  id: string;
  /**
   * @member {string} name The descriptive name of the Workflow
   */
  name: string;
  /**
   * @member {string} teamName The name of the team in which the Workflow is
   * defined
   */
  teamName: string;
  /**
   * @member {string} [description] A description of what the Workflow does
   */
  description?: string;
  /**
   * @member {string} [category] A descriptive grouping for your Workflow
   */
  category?: string;
  /**
   * @member {string} [owner] The email address of the user who owns this
   * Workflow
   */
  owner?: string;
  /**
   * @member {string} [createdBy] The email address of the user who created
   * this Workflow
   */
  createdBy?: string;
  /**
   * @member {Field[]} [inputFields] A collection of the required and optional
   * input fields
   * that can be passed to this Workflow when starting it.
   */
  inputFields?: Field[];
  /**
   * @member {boolean} [isPublished] Indicates whether the Workflow is
   * published; if false, Workflow is in draft mode
   */
  isPublished?: boolean;
  /**
   * @member {boolean} [isArchived] Indicates whether is Archived and no longer
   * available for users to find, start or edit.
   */
  isArchived?: boolean;
  /**
   * @member {FieldVisibility1} [fieldVisibility] Possible values include:
   * 'public', 'internal', 'confidential', 'highlyConfidential'
   */
  fieldVisibility?: FieldVisibility1;
  /**
   * @member {InstanceVisibility} [instanceVisibility] Possible values include:
   * 'open', 'restricted'
   */
  instanceVisibility?: InstanceVisibility;
  /**
   * @member {string[]} [adminUsers] The users who may view, start, and edit
   * this Workflow in addition to Catalytic.Sdk.Entities.Workflow.Owner
   */
  adminUsers?: string[];
  /**
   * @member {string[]} [standardUsers] The users who can view and start this
   * Workflow
   */
  standardUsers?: string[];
  /**
   * @member {number} [taskCountLimit] The maximum number of steps that can
   * appear in an Instance of this Workflow
   */
  taskCountLimit?: number;
  /**
   * @member {number} [fieldCountLimit] The maximum number of fields that can
   * appear in an Instance of this Workflow
   */
  fieldCountLimit?: number;
  /**
   * @member {number} [fieldSizeLimit] The maximum size of data stored in any
   * field in an Instance of this Workflow
   */
  fieldSizeLimit?: number;
  /**
   * @member {number} [fieldTotalSizeLimit] The maximum total size of data
   * stored in all fields in an Instance of this Workflow
   */
  fieldTotalSizeLimit?: number;
  /**
   * @member {number} [dataTableRowLimit] The maximum number of rows of any
   * data table created in an Instance of this Workflow
   */
  dataTableRowLimit?: number;
  /**
   * @member {number} [dataTableColumnLimit] The maximum number of columns of
   * any data table created in an Instance of this Workflow
   */
  dataTableColumnLimit?: number;
  /**
   * @member {number} [dataTableCellLimit] The maximum number of cells of any
   * data table created in an Instance of this Workflow
   */
  dataTableCellLimit?: number;
}

/**
 * @interface
 * An interface representing WorkflowsPage.
 * A page of Workflows returned from a FindAsync request
 *
 */
export interface WorkflowsPage {
  /**
   * @member {Workflow[]} [workflows] The List of Workflows
   */
  workflows?: Workflow[];
  /**
   * @member {PagingOptions} [nextPageOptions]
   */
  nextPageOptions?: PagingOptions;
  /**
   * @member {string} [nextPageToken]
   */
  nextPageToken?: string;
  /**
   * @member {number} [count]
   */
  count?: number;
}

/**
 * @interface
 * An interface representing WorkflowSearchClause.
 */
export interface WorkflowSearchClause {
  /**
   * @member {WorkflowSearchClause[]} [and]
   */
  and?: WorkflowSearchClause[];
  /**
   * @member {WorkflowSearchClause[]} [or]
   */
  or?: WorkflowSearchClause[];
  /**
   * @member {GuidSearchExpression} [id]
   */
  id?: GuidSearchExpression;
  /**
   * @member {StringSearchExpression} [name]
   */
  name?: StringSearchExpression;
  /**
   * @member {StringSearchExpression} [description]
   */
  description?: StringSearchExpression;
  /**
   * @member {StringSearchExpression} [owner]
   */
  owner?: StringSearchExpression;
  /**
   * @member {StringSearchExpression} [category]
   */
  category?: StringSearchExpression;
  /**
   * @member {DateTimeSearchExpression} [createdDate]
   */
  createdDate?: DateTimeSearchExpression;
}

/**
 * @interface
 * An interface representing WorkflowImportRequest.
 * A request to import a Workflow from a .catalytic Workflow Export file
 *
 */
export interface WorkflowImportRequest {
  /**
   * @member {string} [fileId] The FileID of the uploaded .catalytic Workflow
   * Export file
   */
  fileId?: string;
  /**
   * @member {string} [password] The optional password used to secure the
   * .catalytic Workflow Export file
   */
  password?: string;
}

/**
 * @interface
 * An interface representing WorkflowImport.
 * Represents a Workflow Import
 *
 */
export interface WorkflowImport {
  /**
   * @member {string} [id] The Id of the Workflow Import
   */
  id?: string;
  /**
   * @member {string} [name]
   */
  name?: string;
  /**
   * @member {string} [workflowId] The Id of the Workflow created by a
   * successful Import
   */
  workflowId?: string;
  /**
   * @member {string} [errorMessage] The error message produced by a failed
   * Import
   */
  errorMessage?: string;
}

/**
 * @interface
 * An interface representing WorkflowExportRequest.
 * A request to create a .catalytic Workflow Export file
 *
 */
export interface WorkflowExportRequest {
  /**
   * @member {string} [workflowId] The ID of the Workflow to export
   */
  workflowId?: string;
  /**
   * @member {string} [password] The optional password to use to secure the
   * .catalytic Workflow Export file
   */
  password?: string;
}

/**
 * @interface
 * An interface representing WorkflowExport.
 * Represents a Workflow Export
 *
 */
export interface WorkflowExport {
  /**
   * @member {string} [id] The Id of the Workflow Export
   */
  id?: string;
  /**
   * @member {string} [name]
   */
  name?: string;
  /**
   * @member {string} [fileId] The Id of the File created by a successful
   * Export
   */
  fileId?: string;
  /**
   * @member {string} [errorMessage] The error message produced by a failed
   * Export
   */
  errorMessage?: string;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIOptions.
 * @extends ServiceClientOptions
 */
export interface CatalyticSDKAPIOptions extends ServiceClientOptions {
  /**
   * @member {string} [baseUri]
   */
  baseUri?: string;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIFindAccessTokensOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIFindAccessTokensOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [query] Free text query terms to search all attributes
   * for
   */
  query?: string;
  /**
   * @member {string} [status] Run or task status to search for
   */
  status?: string;
  /**
   * @member {string} [processId] Process ID (aka Pushbot ID or Workflow ID) to
   * search for
   */
  processId?: string;
  /**
   * @member {string} [runId] RunID (aka Instance ID) to search for
   */
  runId?: string;
  /**
   * @member {string} [owner] Run or task owner to search for
   */
  owner?: string;
  /**
   * @member {string} [category] Category of process or run to search for
   */
  category?: string;
  /**
   * @member {string} [participatingUsers] Task assignee to search for
   */
  participatingUsers?: string;
  /**
   * @member {string} [startedBefore] Latest start date of the task or run to
   * search for
   */
  startedBefore?: string;
  /**
   * @member {string} [startedAfter] Earliest start date of the task or run to
   * search for
   */
  startedAfter?: string;
  /**
   * @member {string} [endedBefore] Latest end date of the task or run to
   * search for
   */
  endedBefore?: string;
  /**
   * @member {string} [endedAfter] Earliest end date of the task or run to
   * search for
   */
  endedAfter?: string;
  /**
   * @member {string} [pageToken] The token representing the result page to get
   */
  pageToken?: string;
  /**
   * @member {number} [pageSize] The page size requested
   */
  pageSize?: number;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPICreateAccessTokenOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPICreateAccessTokenOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {AccessTokenCreationRequest} [body] Params required to create new
   * AccessToken
   */
  body?: AccessTokenCreationRequest;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPICreateAndApproveAccessTokenOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPICreateAndApproveAccessTokenOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {AccessTokenCreationWithEmailAndPasswordRequest} [body] Params
   * required to create and approve new AccessToken
   */
  body?: AccessTokenCreationWithEmailAndPasswordRequest;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIWaitForAccessTokenApprovalOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIWaitForAccessTokenApprovalOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {WaitForAccessTokenApprovalRequest} [body] Params required to poll
   * approved AccessToken
   */
  body?: WaitForAccessTokenApprovalRequest;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIDownloadDataTableOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIDownloadDataTableOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {Format} [format] The format to export the data table in. csv
   * (default) or excel. Possible values include: 'csv', 'xlsx'
   */
  format?: Format;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIReplaceDataTableOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIReplaceDataTableOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string[]} [files]
   */
  files?: string[];
  /**
   * @member {number} [headerRow] The row number that contains the column
   * headers. Defaults to 1. Default value: 1 .
   */
  headerRow?: number;
  /**
   * @member {number} [sheetNumber] The number of the sheet to import. Only
   * applies to Excel files. The first sheet is imported by default. Default
   * value: 1 .
   */
  sheetNumber?: number;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIUploadDataTableOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIUploadDataTableOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string[]} [files]
   */
  files?: string[];
  /**
   * @member {string} [tableName] The name of the table to create. Defaults to
   * the file name without the extension
   */
  tableName?: string;
  /**
   * @member {number} [headerRow] The row number that contains the column
   * headers. Defaults to 1. Default value: 1 .
   */
  headerRow?: number;
  /**
   * @member {number} [sheetNumber] The number of the sheet to import. Only
   * applies to Excel files. The first sheet is imported by default. Default
   * value: 1 .
   */
  sheetNumber?: number;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIFindDataTablesOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIFindDataTablesOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [query] Free text query terms to search all attributes
   * for
   */
  query?: string;
  /**
   * @member {string} [status] Run or task status to search for
   */
  status?: string;
  /**
   * @member {string} [processId] Process ID (aka Pushbot ID or Workflow ID) to
   * search for
   */
  processId?: string;
  /**
   * @member {string} [runId] RunID (aka Instance ID) to search for
   */
  runId?: string;
  /**
   * @member {string} [owner] Run or task owner to search for
   */
  owner?: string;
  /**
   * @member {string} [category] Category of process or run to search for
   */
  category?: string;
  /**
   * @member {string} [participatingUsers] Task assignee to search for
   */
  participatingUsers?: string;
  /**
   * @member {string} [startedBefore] Latest start date of the task or run to
   * search for
   */
  startedBefore?: string;
  /**
   * @member {string} [startedAfter] Earliest start date of the task or run to
   * search for
   */
  startedAfter?: string;
  /**
   * @member {string} [endedBefore] Latest end date of the task or run to
   * search for
   */
  endedBefore?: string;
  /**
   * @member {string} [endedAfter] Earliest end date of the task or run to
   * search for
   */
  endedAfter?: string;
  /**
   * @member {string} [pageToken] The token representing the result page to get
   */
  pageToken?: string;
  /**
   * @member {number} [pageSize] The page size requested
   */
  pageSize?: number;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIUploadFilesOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIUploadFilesOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string[]} [files]
   */
  files?: string[];
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIFindInstancesOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIFindInstancesOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [query] Free text query terms to search all attributes
   * for
   */
  query?: string;
  /**
   * @member {string} [status] Run or task status to search for
   */
  status?: string;
  /**
   * @member {string} [processId] Process ID (aka Pushbot ID or Workflow ID) to
   * search for
   */
  processId?: string;
  /**
   * @member {string} [runId] RunID (aka Instance ID) to search for
   */
  runId?: string;
  /**
   * @member {string} [owner] Run or task owner to search for
   */
  owner?: string;
  /**
   * @member {string} [category] Category of process or run to search for
   */
  category?: string;
  /**
   * @member {string} [participatingUsers] Task assignee to search for
   */
  participatingUsers?: string;
  /**
   * @member {string} [startedBefore] Latest start date of the task or run to
   * search for
   */
  startedBefore?: string;
  /**
   * @member {string} [startedAfter] Earliest start date of the task or run to
   * search for
   */
  startedAfter?: string;
  /**
   * @member {string} [endedBefore] Latest end date of the task or run to
   * search for
   */
  endedBefore?: string;
  /**
   * @member {string} [endedAfter] Earliest end date of the task or run to
   * search for
   */
  endedAfter?: string;
  /**
   * @member {string} [pageToken] The token representing the result page to get
   */
  pageToken?: string;
  /**
   * @member {number} [pageSize] The page size requested
   */
  pageSize?: number;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIStartInstanceOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIStartInstanceOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {StartInstanceRequest} [body] The details of the Instance to start
   */
  body?: StartInstanceRequest;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIFindInstanceStepsOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIFindInstanceStepsOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [query] Free text query terms to search all attributes
   * for
   */
  query?: string;
  /**
   * @member {string} [status] Run or task status to search for
   */
  status?: string;
  /**
   * @member {string} [processId] Process ID (aka Pushbot ID or Workflow ID) to
   * search for
   */
  processId?: string;
  /**
   * @member {string} [runId] RunID (aka Instance ID) to search for
   */
  runId?: string;
  /**
   * @member {string} [owner] Run or task owner to search for
   */
  owner?: string;
  /**
   * @member {string} [category] Category of process or run to search for
   */
  category?: string;
  /**
   * @member {string} [participatingUsers] Task assignee to search for
   */
  participatingUsers?: string;
  /**
   * @member {string} [startedBefore] Latest start date of the task or run to
   * search for
   */
  startedBefore?: string;
  /**
   * @member {string} [startedAfter] Earliest start date of the task or run to
   * search for
   */
  startedAfter?: string;
  /**
   * @member {string} [endedBefore] Latest end date of the task or run to
   * search for
   */
  endedBefore?: string;
  /**
   * @member {string} [endedAfter] Earliest end date of the task or run to
   * search for
   */
  endedAfter?: string;
  /**
   * @member {string} [pageToken] The token representing the result page to get
   */
  pageToken?: string;
  /**
   * @member {number} [pageSize] The page size requested
   */
  pageSize?: number;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPICompleteStepOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPICompleteStepOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {CompleteStepRequest} [body] The values of the fields to complete
   * the task with
   */
  body?: CompleteStepRequest;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIReassignStepOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIReassignStepOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {ReassignStepRequest} [body] Contains the email address of the
   * user to reassign the Instance Step to
   */
  body?: ReassignStepRequest;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIFindIntegrationsOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIFindIntegrationsOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [query] Free text query terms to search all attributes
   * for
   */
  query?: string;
  /**
   * @member {string} [status] Run or task status to search for
   */
  status?: string;
  /**
   * @member {string} [processId] Process ID (aka Pushbot ID or Workflow ID) to
   * search for
   */
  processId?: string;
  /**
   * @member {string} [runId] RunID (aka Instance ID) to search for
   */
  runId?: string;
  /**
   * @member {string} [owner] Run or task owner to search for
   */
  owner?: string;
  /**
   * @member {string} [category] Category of process or run to search for
   */
  category?: string;
  /**
   * @member {string} [participatingUsers] Task assignee to search for
   */
  participatingUsers?: string;
  /**
   * @member {string} [startedBefore] Latest start date of the task or run to
   * search for
   */
  startedBefore?: string;
  /**
   * @member {string} [startedAfter] Earliest start date of the task or run to
   * search for
   */
  startedAfter?: string;
  /**
   * @member {string} [endedBefore] Latest end date of the task or run to
   * search for
   */
  endedBefore?: string;
  /**
   * @member {string} [endedAfter] Earliest end date of the task or run to
   * search for
   */
  endedAfter?: string;
  /**
   * @member {string} [pageToken] The token representing the result page to get
   */
  pageToken?: string;
  /**
   * @member {number} [pageSize] The page size requested
   */
  pageSize?: number;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPICreateIntegrationOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPICreateIntegrationOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {IntegrationCreationRequest} [body] The definition of the action
   * to create
   */
  body?: IntegrationCreationRequest;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIUpdateIntegrationOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIUpdateIntegrationOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {IntegrationUpdateRequest} [body] The updates to apply to the
   * action
   */
  body?: IntegrationUpdateRequest;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIUpdateIntegrationUnencodedOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIUpdateIntegrationUnencodedOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {IntegrationUpdateRequest} [body] The updates to apply to the
   * action
   */
  body?: IntegrationUpdateRequest;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPICreateIntegrationConnectionOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPICreateIntegrationConnectionOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {IntegrationConnectionCreationRequest} [body] Request containing
   * information used to create the Integration Connection
   */
  body?: IntegrationConnectionCreationRequest;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPICreateIntegrationConnectionUnencodedOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPICreateIntegrationConnectionUnencodedOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {IntegrationConnectionCreationRequest} [body] Request containing
   * information used to create the Integration Connection
   */
  body?: IntegrationConnectionCreationRequest;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIFindUsersOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIFindUsersOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [query] Free text query terms to search all attributes
   * for
   */
  query?: string;
  /**
   * @member {string} [status] Run or task status to search for
   */
  status?: string;
  /**
   * @member {string} [processId] Process ID (aka Pushbot ID or Workflow ID) to
   * search for
   */
  processId?: string;
  /**
   * @member {string} [runId] RunID (aka Instance ID) to search for
   */
  runId?: string;
  /**
   * @member {string} [owner] Run or task owner to search for
   */
  owner?: string;
  /**
   * @member {string} [category] Category of process or run to search for
   */
  category?: string;
  /**
   * @member {string} [participatingUsers] Task assignee to search for
   */
  participatingUsers?: string;
  /**
   * @member {string} [startedBefore] Latest start date of the task or run to
   * search for
   */
  startedBefore?: string;
  /**
   * @member {string} [startedAfter] Earliest start date of the task or run to
   * search for
   */
  startedAfter?: string;
  /**
   * @member {string} [endedBefore] Latest end date of the task or run to
   * search for
   */
  endedBefore?: string;
  /**
   * @member {string} [endedAfter] Earliest end date of the task or run to
   * search for
   */
  endedAfter?: string;
  /**
   * @member {string} [pageToken] The token representing the result page to get
   */
  pageToken?: string;
  /**
   * @member {number} [pageSize] The page size requested
   */
  pageSize?: number;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPISearchUsersOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPISearchUsersOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {UserSearchClause} [body]
   */
  body?: UserSearchClause;
  /**
   * @member {string} [pageToken] The token representing the result page to get
   */
  pageToken?: string;
  /**
   * @member {number} [pageSize] The page size requested
   */
  pageSize?: number;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIFindWorkflowsOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIFindWorkflowsOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [query] Free text query terms to search all attributes
   * for
   */
  query?: string;
  /**
   * @member {string} [status] Run or task status to search for
   */
  status?: string;
  /**
   * @member {string} [processId] Process ID (aka Pushbot ID or Workflow ID) to
   * search for
   */
  processId?: string;
  /**
   * @member {string} [runId] RunID (aka Instance ID) to search for
   */
  runId?: string;
  /**
   * @member {string} [owner] Run or task owner to search for
   */
  owner?: string;
  /**
   * @member {string} [category] Category of process or run to search for
   */
  category?: string;
  /**
   * @member {string} [participatingUsers] Task assignee to search for
   */
  participatingUsers?: string;
  /**
   * @member {string} [startedBefore] Latest start date of the task or run to
   * search for
   */
  startedBefore?: string;
  /**
   * @member {string} [startedAfter] Earliest start date of the task or run to
   * search for
   */
  startedAfter?: string;
  /**
   * @member {string} [endedBefore] Latest end date of the task or run to
   * search for
   */
  endedBefore?: string;
  /**
   * @member {string} [endedAfter] Earliest end date of the task or run to
   * search for
   */
  endedAfter?: string;
  /**
   * @member {string} [pageToken] The token representing the result page to get
   */
  pageToken?: string;
  /**
   * @member {number} [pageSize] The page size requested
   */
  pageSize?: number;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPISearchWorkflowsOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPISearchWorkflowsOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {WorkflowSearchClause} [body]
   */
  body?: WorkflowSearchClause;
  /**
   * @member {string} [pageToken] The token representing the result page to get
   */
  pageToken?: string;
  /**
   * @member {number} [pageSize] The page size requested
   */
  pageSize?: number;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIImportWorkflowOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIImportWorkflowOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {WorkflowImportRequest} [body] The Workflow Import request
   */
  body?: WorkflowImportRequest;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIExportWorkflowOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIExportWorkflowOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {WorkflowExportRequest} [body] The Workflow Export request
   */
  body?: WorkflowExportRequest;
}

/**
 * Defines values for Type.
 * Possible values include: 'user', 'actionWorker'
 * @readonly
 * @enum {string}
 */
export type Type = 'user' | 'actionWorker';

/**
 * Defines values for Type1.
 * Possible values include: 'undefined', 'text', 'integer', 'decimal', 'date', 'dateTime', 'json',
 * 'bool', 'singleChoice', 'multipleChoice', 'instructions', 'file', 'table', 'workflow',
 * 'instance', 'user', 'password'
 * @readonly
 * @enum {string}
 */
export type Type1 = 'undefined' | 'text' | 'integer' | 'decimal' | 'date' | 'dateTime' | 'json' | 'bool' | 'singleChoice' | 'multipleChoice' | 'instructions' | 'file' | 'table' | 'workflow' | 'instance' | 'user' | 'password';

/**
 * Defines values for Type2.
 * Possible values include: 'imported', 'master', 'application', 'instance', 'batch'
 * @readonly
 * @enum {string}
 */
export type Type2 = 'imported' | 'master' | 'application' | 'instance' | 'batch';

/**
 * Defines values for Visibility.
 * Possible values include: 'open', 'restricted'
 * @readonly
 * @enum {string}
 */
export type Visibility = 'open' | 'restricted';

/**
 * Defines values for FieldType.
 * Possible values include: 'undefined', 'text', 'integer', 'decimal', 'date', 'dateTime', 'json',
 * 'bool', 'singleChoice', 'multipleChoice', 'instructions', 'file', 'table', 'workflow',
 * 'instance', 'user', 'password'
 * @readonly
 * @enum {string}
 */
export type FieldType = 'undefined' | 'text' | 'integer' | 'decimal' | 'date' | 'dateTime' | 'json' | 'bool' | 'singleChoice' | 'multipleChoice' | 'instructions' | 'file' | 'table' | 'workflow' | 'instance' | 'user' | 'password';

/**
 * Defines values for Status.
 * Possible values include: 'pending', 'active', 'completed', 'cancelled', 'snoozed', 'skipped',
 * 'error'
 * @readonly
 * @enum {string}
 */
export type Status = 'pending' | 'active' | 'completed' | 'cancelled' | 'snoozed' | 'skipped' | 'error';

/**
 * Defines values for Status1.
 * Possible values include: 'running', 'completed', 'cancelled'
 * @readonly
 * @enum {string}
 */
export type Status1 = 'running' | 'completed' | 'cancelled';

/**
 * Defines values for FieldVisibility.
 * Possible values include: 'public', 'internal', 'confidential', 'highlyConfidential'
 * @readonly
 * @enum {string}
 */
export type FieldVisibility = 'public' | 'internal' | 'confidential' | 'highlyConfidential';

/**
 * Defines values for Visibility1.
 * Possible values include: 'open', 'restricted'
 * @readonly
 * @enum {string}
 */
export type Visibility1 = 'open' | 'restricted';

/**
 * Defines values for FieldVisibility1.
 * Possible values include: 'public', 'internal', 'confidential', 'highlyConfidential'
 * @readonly
 * @enum {string}
 */
export type FieldVisibility1 = 'public' | 'internal' | 'confidential' | 'highlyConfidential';

/**
 * Defines values for InstanceVisibility.
 * Possible values include: 'open', 'restricted'
 * @readonly
 * @enum {string}
 */
export type InstanceVisibility = 'open' | 'restricted';

/**
 * Defines values for Format.
 * Possible values include: 'csv', 'xlsx'
 * @readonly
 * @enum {string}
 */
export type Format = 'csv' | 'xlsx';

/**
 * Contains response data for the findAccessTokens operation.
 */
export type FindAccessTokensResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getAccessToken operation.
 */
export type GetAccessTokenResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the revokeAccessToken operation.
 */
export type RevokeAccessTokenResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the createAccessToken operation.
 */
export type CreateAccessTokenResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the createAndApproveAccessToken operation.
 */
export type CreateAndApproveAccessTokenResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the waitForAccessTokenApproval operation.
 */
export type WaitForAccessTokenApprovalResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getDataTable operation.
 */
export type GetDataTableResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the downloadDataTable operation.
 */
export type DownloadDataTableResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the replaceDataTable operation.
 */
export type ReplaceDataTableResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the uploadDataTable operation.
 */
export type UploadDataTableResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the findDataTables operation.
 */
export type FindDataTablesResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getFile operation.
 */
export type GetFileResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the downloadFile operation.
 */
export type DownloadFileResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the uploadFiles operation.
 */
export type UploadFilesResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the findInstances operation.
 */
export type FindInstancesResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the startInstance operation.
 */
export type StartInstanceResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getInstance operation.
 */
export type GetInstanceResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the stopInstance operation.
 */
export type StopInstanceResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the findInstanceSteps operation.
 */
export type FindInstanceStepsResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getInstanceStep operation.
 */
export type GetInstanceStepResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the completeStep operation.
 */
export type CompleteStepResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the startStep operation.
 */
export type StartStepResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the snoozeStep operation.
 */
export type SnoozeStepResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the reassignStep operation.
 */
export type ReassignStepResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the findIntegrations operation.
 */
export type FindIntegrationsResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the createIntegration operation.
 */
export type CreateIntegrationResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getIntegration operation.
 */
export type GetIntegrationResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the updateIntegration operation.
 */
export type UpdateIntegrationResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the deleteIntegration operation.
 */
export type DeleteIntegrationResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getIntegrationUnencoded operation.
 */
export type GetIntegrationUnencodedResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the updateIntegrationUnencoded operation.
 */
export type UpdateIntegrationUnencodedResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the deleteIntegrationUnencoded operation.
 */
export type DeleteIntegrationUnencodedResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the createIntegrationConnection operation.
 */
export type CreateIntegrationConnectionResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the createIntegrationConnectionUnencoded operation.
 */
export type CreateIntegrationConnectionUnencodedResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getIntegrationConnection operation.
 */
export type GetIntegrationConnectionResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the deleteIntegrationConnection operation.
 */
export type DeleteIntegrationConnectionResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getIntegrationConnectionUnencoded operation.
 */
export type GetIntegrationConnectionUnencodedResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the deleteIntegrationConnectionUnencoded operation.
 */
export type DeleteIntegrationConnectionUnencodedResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getUser operation.
 */
export type GetUserResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the findUsers operation.
 */
export type FindUsersResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the searchUsers operation.
 */
export type SearchUsersResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the findWorkflows operation.
 */
export type FindWorkflowsResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the searchWorkflows operation.
 */
export type SearchWorkflowsResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getWorkflow operation.
 */
export type GetWorkflowResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the importWorkflow operation.
 */
export type ImportWorkflowResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getWorkflowImport operation.
 */
export type GetWorkflowImportResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the exportWorkflow operation.
 */
export type ExportWorkflowResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getWorkflowExport operation.
 */
export type GetWorkflowExportResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};
