/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import { ServiceClientOptions } from "@azure/ms-rest-js";
import * as msRest from "@azure/ms-rest-js";


/**
 * @interface
 * An interface representing ProblemDetails.
 */
export interface ProblemDetails {
  /**
   * @member {string} [type]
   */
  type?: string;
  /**
   * @member {string} [title]
   */
  title?: string;
  /**
   * @member {number} [status]
   */
  status?: number;
  /**
   * @member {string} [detail]
   */
  detail?: string;
  /**
   * @member {string} [instance]
   */
  instance?: string;
  /**
   * @member {{ [propertyName: string]: any }} [extensions] **NOTE: This
   * property will not be serialized. It can only be populated by the server.**
   */
  readonly extensions?: { [propertyName: string]: any };
}

/**
 * @interface
 * An interface representing ActionInputDefinition.
 */
export interface ActionInputDefinition {
  /**
   * @member {boolean} [isRequired]
   */
  isRequired?: boolean;
  /**
   * @member {string} [defaultValueSerialized]
   */
  defaultValueSerialized?: string;
  /**
   * @member {string} [name]
   */
  name?: string;
  /**
   * @member {string} [description]
   */
  description?: string;
  /**
   * @member {Type} [type] Possible values include: 'undefined', 'text',
   * 'integer', 'decimal', 'date', 'dateTime', 'boolean', 'singleChoice',
   * 'multipleChoice', 'json', 'file', 'table', 'pushbot', 'instance', 'user'
   */
  type?: Type;
}

/**
 * @interface
 * An interface representing ActionOutputDefinition.
 */
export interface ActionOutputDefinition {
  /**
   * @member {string} [name]
   */
  name?: string;
  /**
   * @member {string} [description]
   */
  description?: string;
  /**
   * @member {Type1} [type] Possible values include: 'undefined', 'text',
   * 'integer', 'decimal', 'date', 'dateTime', 'boolean', 'singleChoice',
   * 'multipleChoice', 'json', 'file', 'table', 'pushbot', 'instance', 'user'
   */
  type?: Type1;
}

/**
 * @interface
 * An interface representing Action.
 */
export interface Action {
  /**
   * @member {string} [id]
   */
  id?: string;
  /**
   * @member {string} [teamName]
   */
  teamName?: string;
  /**
   * @member {string} [name]
   */
  name?: string;
  /**
   * @member {string} [description]
   */
  description?: string;
  /**
   * @member {string[]} [tags] **NOTE: This property will not be serialized. It
   * can only be populated by the server.**
   */
  readonly tags?: string[];
  /**
   * @member {string[]} [requiredWorkerTags] **NOTE: This property will not be
   * serialized. It can only be populated by the server.**
   */
  readonly requiredWorkerTags?: string[];
  /**
   * @member {ActionInputDefinition[]} [inputs] **NOTE: This property will not
   * be serialized. It can only be populated by the server.**
   */
  readonly inputs?: ActionInputDefinition[];
  /**
   * @member {ActionOutputDefinition[]} [outputs] **NOTE: This property will
   * not be serialized. It can only be populated by the server.**
   */
  readonly outputs?: ActionOutputDefinition[];
  /**
   * @member {boolean} [isPublished]
   */
  isPublished?: boolean;
}

/**
 * @interface
 * An interface representing ActionsPage.
 */
export interface ActionsPage {
  /**
   * @member {Action[]} [actions] **NOTE: This property will not be serialized.
   * It can only be populated by the server.**
   */
  readonly actions?: Action[];
  /**
   * @member {string} [nextPageToken]
   */
  nextPageToken?: string;
  /**
   * @member {number} [count] **NOTE: This property will not be serialized. It
   * can only be populated by the server.**
   */
  readonly count?: number;
}

/**
 * @interface
 * An interface representing RegisterActionRequest.
 */
export interface RegisterActionRequest {
  /**
   * @member {string} [name]
   */
  name?: string;
  /**
   * @member {string} [description]
   */
  description?: string;
  /**
   * @member {string[]} [tags] **NOTE: This property will not be serialized. It
   * can only be populated by the server.**
   */
  readonly tags?: string[];
  /**
   * @member {string[]} [requiredWorkerTags] **NOTE: This property will not be
   * serialized. It can only be populated by the server.**
   */
  readonly requiredWorkerTags?: string[];
  /**
   * @member {ActionInputDefinition[]} [inputs] **NOTE: This property will not
   * be serialized. It can only be populated by the server.**
   */
  readonly inputs?: ActionInputDefinition[];
  /**
   * @member {ActionOutputDefinition[]} [outputs] **NOTE: This property will
   * not be serialized. It can only be populated by the server.**
   */
  readonly outputs?: ActionOutputDefinition[];
  /**
   * @member {boolean} [isPublished]
   */
  isPublished?: boolean;
}

/**
 * @interface
 * An interface representing UpdateActionRequest.
 */
export interface UpdateActionRequest {
  /**
   * @member {string} [name]
   */
  name?: string;
  /**
   * @member {string} [description]
   */
  description?: string;
  /**
   * @member {string[]} [tags]
   */
  tags?: string[];
  /**
   * @member {string[]} [requiredWorkerTags]
   */
  requiredWorkerTags?: string[];
  /**
   * @member {boolean} [isPublished]
   */
  isPublished?: boolean;
}

/**
 * @interface
 * An interface representing ActionWorker.
 */
export interface ActionWorker {
  /**
   * @member {string} [id]
   */
  id?: string;
  /**
   * @member {string} [teamName]
   */
  teamName?: string;
  /**
   * @member {string} [name]
   */
  name?: string;
  /**
   * @member {string} [description]
   */
  description?: string;
  /**
   * @member {string[]} [tags] **NOTE: This property will not be serialized. It
   * can only be populated by the server.**
   */
  readonly tags?: string[];
  /**
   * @member {string} [hostname]
   */
  hostname?: string;
  /**
   * @member {string} [ipAddress]
   */
  ipAddress?: string;
  /**
   * @member {string[]} [implementedActionIds] **NOTE: This property will not
   * be serialized. It can only be populated by the server.**
   */
  readonly implementedActionIds?: string[];
  /**
   * @member {Date} [lastSeenTime]
   */
  lastSeenTime?: Date;
}

/**
 * @interface
 * An interface representing ActionWorkersPage.
 */
export interface ActionWorkersPage {
  /**
   * @member {ActionWorker[]} [actionWorkers] **NOTE: This property will not be
   * serialized. It can only be populated by the server.**
   */
  readonly actionWorkers?: ActionWorker[];
  /**
   * @member {string} [nextPageToken]
   */
  nextPageToken?: string;
  /**
   * @member {number} [count] **NOTE: This property will not be serialized. It
   * can only be populated by the server.**
   */
  readonly count?: number;
}

/**
 * @interface
 * An interface representing CreateActionWorkerRequest.
 */
export interface CreateActionWorkerRequest {
  /**
   * @member {string} [name]
   */
  name?: string;
  /**
   * @member {string} [description]
   */
  description?: string;
  /**
   * @member {string[]} [tags]
   */
  tags?: string[];
  /**
   * @member {string} [hostname]
   */
  hostname?: string;
  /**
   * @member {string} [ipAddress]
   */
  ipAddress?: string;
  /**
   * @member {string[]} [implementedActionIds]
   */
  implementedActionIds?: string[];
}

/**
 * @interface
 * An interface representing ActionWorkerWithCredentials.
 */
export interface ActionWorkerWithCredentials {
  /**
   * @member {string} [secretKey]
   */
  secretKey?: string;
  /**
   * @member {string} [id]
   */
  id?: string;
  /**
   * @member {string} [teamName]
   */
  teamName?: string;
  /**
   * @member {string} [name]
   */
  name?: string;
  /**
   * @member {string} [description]
   */
  description?: string;
  /**
   * @member {string[]} [tags] **NOTE: This property will not be serialized. It
   * can only be populated by the server.**
   */
  readonly tags?: string[];
  /**
   * @member {string} [hostname]
   */
  hostname?: string;
  /**
   * @member {string} [ipAddress]
   */
  ipAddress?: string;
  /**
   * @member {string[]} [implementedActionIds] **NOTE: This property will not
   * be serialized. It can only be populated by the server.**
   */
  readonly implementedActionIds?: string[];
  /**
   * @member {Date} [lastSeenTime]
   */
  lastSeenTime?: Date;
}

/**
 * @interface
 * An interface representing UpdateActionWorkerRequest.
 */
export interface UpdateActionWorkerRequest {
  /**
   * @member {string} [id]
   */
  id?: string;
  /**
   * @member {string} [name]
   */
  name?: string;
  /**
   * @member {string} [description]
   */
  description?: string;
  /**
   * @member {string[]} [tags]
   */
  tags?: string[];
  /**
   * @member {string} [hostname]
   */
  hostname?: string;
  /**
   * @member {string} [ipAddress]
   */
  ipAddress?: string;
  /**
   * @member {string[]} [implementedActionIds]
   */
  implementedActionIds?: string[];
}

/**
 * @interface
 * An interface representing CreateDeveloperKeyRequest.
 */
export interface CreateDeveloperKeyRequest {
  /**
   * @member {string} domain
   */
  domain: string;
}

/**
 * @interface
 * An interface representing DeveloperKey.
 */
export interface DeveloperKey {
  /**
   * @member {string} accessIdentifier
   */
  accessIdentifier: string;
  /**
   * @member {string} [secret]
   */
  secret?: string;
  /**
   * @member {Status} status Possible values include: 'requested', 'approved',
   * 'active', 'revoked'
   */
  status: Status;
  /**
   * @member {string} [createdById]
   */
  createdById?: string;
  /**
   * @member {string} domain
   */
  domain: string;
  /**
   * @member {string} [name]
   */
  name?: string;
  /**
   * @member {string} [referenceName] **NOTE: This property will not be
   * serialized. It can only be populated by the server.**
   */
  readonly referenceName?: string;
  /**
   * @member {string} [id] **NOTE: This property will not be serialized. It can
   * only be populated by the server.**
   */
  readonly id?: string;
}

/**
 * @interface
 * An interface representing DeveloperKeyActivationRequest.
 */
export interface DeveloperKeyActivationRequest {
  /**
   * @member {string} domain
   */
  domain: string;
  /**
   * @member {string} accessIdentifier
   */
  accessIdentifier: string;
  /**
   * @member {number} [requestTimeoutMS]
   */
  requestTimeoutMS?: number;
}

/**
 * @interface
 * An interface representing FieldRestrictions.
 */
export interface FieldRestrictions {
  /**
   * @member {string[]} [choices] **NOTE: This property will not be serialized.
   * It can only be populated by the server.**
   */
  readonly choices?: string[];
  /**
   * @member {boolean} [valueRequired]
   */
  valueRequired?: boolean;
}

/**
 * @interface
 * An interface representing DataTableColumn.
 */
export interface DataTableColumn {
  /**
   * @member {string} [name]
   */
  name?: string;
  /**
   * @member {Type2} [type] Possible values include: 'undefined', 'text',
   * 'integer', 'decimal', 'date', 'dateTime', 'json', 'bool', 'singleChoice',
   * 'multipleChoice', 'instructions', 'file', 'table', 'pushbot', 'instance',
   * 'user'
   */
  type?: Type2;
  /**
   * @member {string} [referenceName]
   */
  referenceName?: string;
  /**
   * @member {FieldRestrictions} [restrictions]
   */
  restrictions?: FieldRestrictions;
}

/**
 * @interface
 * An interface representing DataTable.
 */
export interface DataTable {
  /**
   * @member {string} id
   */
  id: string;
  /**
   * @member {string} [dataTableId] **NOTE: This property will not be
   * serialized. It can only be populated by the server.**
   */
  readonly dataTableId?: string;
  /**
   * @member {string} [referenceName] **NOTE: This property will not be
   * serialized. It can only be populated by the server.**
   */
  readonly referenceName?: string;
  /**
   * @member {string} name
   */
  name: string;
  /**
   * @member {string} teamName
   */
  teamName: string;
  /**
   * @member {string} [description]
   */
  description?: string;
  /**
   * @member {DataTableColumn[]} [columns] **NOTE: This property will not be
   * serialized. It can only be populated by the server.**
   */
  readonly columns?: DataTableColumn[];
  /**
   * @member {boolean} [isArchived]
   */
  isArchived?: boolean;
  /**
   * @member {Type3} [type] Possible values include: 'imported', 'master',
   * 'application', 'instance', 'batch'
   */
  type?: Type3;
  /**
   * @member {Visibility} [visibility] Possible values include: 'open',
   * 'restricted'
   */
  visibility?: Visibility;
  /**
   * @member {string[]} [adminUsers] **NOTE: This property will not be
   * serialized. It can only be populated by the server.**
   */
  readonly adminUsers?: string[];
  /**
   * @member {string[]} [standardUsers] **NOTE: This property will not be
   * serialized. It can only be populated by the server.**
   */
  readonly standardUsers?: string[];
  /**
   * @member {string[]} [readOnlyUsers] **NOTE: This property will not be
   * serialized. It can only be populated by the server.**
   */
  readonly readOnlyUsers?: string[];
  /**
   * @member {number} [rowLimit]
   */
  rowLimit?: number;
  /**
   * @member {number} [columnLimit]
   */
  columnLimit?: number;
  /**
   * @member {number} [cellLimit]
   */
  cellLimit?: number;
}

/**
 * @interface
 * An interface representing DataTablesPage.
 */
export interface DataTablesPage {
  /**
   * @member {DataTable[]} [dataTables] **NOTE: This property will not be
   * serialized. It can only be populated by the server.**
   */
  readonly dataTables?: DataTable[];
  /**
   * @member {string} [nextPageToken]
   */
  nextPageToken?: string;
  /**
   * @member {number} [count] **NOTE: This property will not be serialized. It
   * can only be populated by the server.**
   */
  readonly count?: number;
}

/**
 * @interface
 * An interface representing DeveloperKeysPage.
 */
export interface DeveloperKeysPage {
  /**
   * @member {DeveloperKey[]} [developerKeys] **NOTE: This property will not be
   * serialized. It can only be populated by the server.**
   */
  readonly developerKeys?: DeveloperKey[];
  /**
   * @member {string} [nextPageToken]
   */
  nextPageToken?: string;
  /**
   * @member {number} [count] **NOTE: This property will not be serialized. It
   * can only be populated by the server.**
   */
  readonly count?: number;
}

/**
 * @interface
 * An interface representing File.
 */
export interface File {
  /**
   * @member {string} [id]
   */
  id?: string;
  /**
   * @member {string} [name]
   */
  name?: string;
  /**
   * @member {string} [teamName]
   */
  teamName?: string;
  /**
   * @member {string} [contentType]
   */
  contentType?: string;
  /**
   * @member {number} [sizeInBytes]
   */
  sizeInBytes?: number;
  /**
   * @member {string} [displaySize]
   */
  displaySize?: string;
  /**
   * @member {boolean} [isPublic]
   */
  isPublic?: boolean;
  /**
   * @member {string} [md5Hash]
   */
  md5Hash?: string;
  /**
   * @member {string} [referenceName] **NOTE: This property will not be
   * serialized. It can only be populated by the server.**
   */
  readonly referenceName?: string;
}

/**
 * @interface
 * An interface representing FilesPage.
 */
export interface FilesPage {
  /**
   * @member {File[]} [files] **NOTE: This property will not be serialized. It
   * can only be populated by the server.**
   */
  readonly files?: File[];
  /**
   * @member {string} [nextPageToken]
   */
  nextPageToken?: string;
  /**
   * @member {number} [count] **NOTE: This property will not be serialized. It
   * can only be populated by the server.**
   */
  readonly count?: number;
}

/**
 * @interface
 * An interface representing InstanceStep.
 */
export interface InstanceStep {
  /**
   * @member {string} id
   */
  id: string;
  /**
   * @member {string} instanceId
   */
  instanceId: string;
  /**
   * @member {string} pushbotId
   */
  pushbotId: string;
  /**
   * @member {string} name
   */
  name: string;
  /**
   * @member {string} referenceName
   */
  referenceName: string;
  /**
   * @member {string} teamName
   */
  teamName: string;
  /**
   * @member {number} [position]
   */
  position?: number;
  /**
   * @member {string} [description]
   */
  description?: string;
  /**
   * @member {Status1} [status] Possible values include: 'pending', 'active',
   * 'completed', 'cancelled', 'snoozed', 'skipped', 'error'
   */
  status?: Status1;
  /**
   * @member {string} [assignedTo]
   */
  assignedTo?: string;
}

/**
 * @interface
 * An interface representing Field.
 */
export interface Field {
  /**
   * @member {string} [id]
   */
  id?: string;
  /**
   * @member {string} [name]
   */
  name?: string;
  /**
   * @member {string} [referenceName]
   */
  referenceName?: string;
  /**
   * @member {string} [description]
   */
  description?: string;
  /**
   * @member {number} [position]
   */
  position?: number;
  /**
   * @member {FieldRestrictions} [restrictions]
   */
  restrictions?: FieldRestrictions;
  /**
   * @member {FieldType} [fieldType] Possible values include: 'undefined',
   * 'text', 'integer', 'decimal', 'date', 'dateTime', 'json', 'bool',
   * 'singleChoice', 'multipleChoice', 'instructions', 'file', 'table',
   * 'pushbot', 'instance', 'user'
   */
  fieldType?: FieldType;
  /**
   * @member {string} [value]
   */
  value?: string;
  /**
   * @member {string} [defaultValue]
   */
  defaultValue?: string;
}

/**
 * @interface
 * An interface representing Instance.
 */
export interface Instance {
  /**
   * @member {string} id
   */
  id: string;
  /**
   * @member {string} pushbotId
   */
  pushbotId: string;
  /**
   * @member {string} [name]
   */
  name?: string;
  /**
   * @member {string} teamName
   */
  teamName: string;
  /**
   * @member {string} [description]
   */
  description?: string;
  /**
   * @member {string} [category]
   */
  category?: string;
  /**
   * @member {InstanceStep[]} [steps] **NOTE: This property will not be
   * serialized. It can only be populated by the server.**
   */
  readonly steps?: InstanceStep[];
  /**
   * @member {Field[]} [fields] **NOTE: This property will not be serialized.
   * It can only be populated by the server.**
   */
  readonly fields?: Field[];
  /**
   * @member {Status2} [status] Possible values include: 'running',
   * 'completed', 'cancelled'
   */
  status?: Status2;
  /**
   * @member {FieldVisibility} [fieldVisibility] Possible values include:
   * 'public', 'internal', 'confidential', 'highlyConfidential'
   */
  fieldVisibility?: FieldVisibility;
  /**
   * @member {Visibility1} [visibility] Possible values include: 'open',
   * 'restricted'
   */
  visibility?: Visibility1;
  /**
   * @member {string[]} [adminUsers] **NOTE: This property will not be
   * serialized. It can only be populated by the server.**
   */
  readonly adminUsers?: string[];
  /**
   * @member {string[]} [standardUsers] **NOTE: This property will not be
   * serialized. It can only be populated by the server.**
   */
  readonly standardUsers?: string[];
}

/**
 * @interface
 * An interface representing InstancesPage.
 */
export interface InstancesPage {
  /**
   * @member {Instance[]} [instances] **NOTE: This property will not be
   * serialized. It can only be populated by the server.**
   */
  readonly instances?: Instance[];
  /**
   * @member {string} [nextPageToken]
   */
  nextPageToken?: string;
  /**
   * @member {number} [count] **NOTE: This property will not be serialized. It
   * can only be populated by the server.**
   */
  readonly count?: number;
}

/**
 * @interface
 * An interface representing InstanceInputField.
 */
export interface InstanceInputField {
  /**
   * @member {string} [name]
   */
  name?: string;
  /**
   * @member {string} [referenceName]
   */
  referenceName?: string;
  /**
   * @member {string} [value]
   */
  value?: string;
}

/**
 * @interface
 * An interface representing StartInstanceRequest.
 */
export interface StartInstanceRequest {
  /**
   * @member {string} [pushbotId]
   */
  pushbotId?: string;
  /**
   * @member {string} [name]
   */
  name?: string;
  /**
   * @member {string} [description]
   */
  description?: string;
  /**
   * @member {InstanceInputField[]} [inputFields] **NOTE: This property will
   * not be serialized. It can only be populated by the server.**
   */
  readonly inputFields?: InstanceInputField[];
}

/**
 * @interface
 * An interface representing InstanceStepsPage.
 */
export interface InstanceStepsPage {
  /**
   * @member {InstanceStep[]} [steps] **NOTE: This property will not be
   * serialized. It can only be populated by the server.**
   */
  readonly steps?: InstanceStep[];
  /**
   * @member {string} [nextPageToken]
   */
  nextPageToken?: string;
  /**
   * @member {number} [count] **NOTE: This property will not be serialized. It
   * can only be populated by the server.**
   */
  readonly count?: number;
}

/**
 * @interface
 * An interface representing CompleteStepRequest.
 */
export interface CompleteStepRequest {
  /**
   * @member {string} [id]
   */
  id?: string;
  /**
   * @member {InstanceInputField[]} [stepOutputFields] **NOTE: This property
   * will not be serialized. It can only be populated by the server.**
   */
  readonly stepOutputFields?: InstanceInputField[];
}

/**
 * @interface
 * An interface representing ReassignTaskRequest.
 */
export interface ReassignTaskRequest {
  /**
   * @member {string} [assignTo]
   */
  assignTo?: string;
}

/**
 * @interface
 * An interface representing Pushbot.
 */
export interface Pushbot {
  /**
   * @member {string} id
   */
  id: string;
  /**
   * @member {string} name
   */
  name: string;
  /**
   * @member {string} teamName
   */
  teamName: string;
  /**
   * @member {string} [description]
   */
  description?: string;
  /**
   * @member {string} [category]
   */
  category?: string;
  /**
   * @member {Field[]} [inputFields] **NOTE: This property will not be
   * serialized. It can only be populated by the server.**
   */
  readonly inputFields?: Field[];
  /**
   * @member {boolean} [isPublished]
   */
  isPublished?: boolean;
  /**
   * @member {boolean} [isArchived]
   */
  isArchived?: boolean;
  /**
   * @member {FieldVisibility1} [fieldVisibility] Possible values include:
   * 'public', 'internal', 'confidential', 'highlyConfidential'
   */
  fieldVisibility?: FieldVisibility1;
  /**
   * @member {InstanceVisibility} [instanceVisibility] Possible values include:
   * 'open', 'restricted'
   */
  instanceVisibility?: InstanceVisibility;
  /**
   * @member {string[]} [adminUsers] **NOTE: This property will not be
   * serialized. It can only be populated by the server.**
   */
  readonly adminUsers?: string[];
  /**
   * @member {string[]} [standardUsers] **NOTE: This property will not be
   * serialized. It can only be populated by the server.**
   */
  readonly standardUsers?: string[];
  /**
   * @member {string[]} [readOnlyUsers] **NOTE: This property will not be
   * serialized. It can only be populated by the server.**
   */
  readonly readOnlyUsers?: string[];
  /**
   * @member {number} [taskCountLimit]
   */
  taskCountLimit?: number;
  /**
   * @member {number} [fieldCountLimit]
   */
  fieldCountLimit?: number;
  /**
   * @member {number} [fieldSizeLimit]
   */
  fieldSizeLimit?: number;
  /**
   * @member {number} [fieldTotalSizeLimit]
   */
  fieldTotalSizeLimit?: number;
  /**
   * @member {number} [dataTableRowLimit]
   */
  dataTableRowLimit?: number;
  /**
   * @member {number} [dataTableColumnLimit]
   */
  dataTableColumnLimit?: number;
  /**
   * @member {number} [dataTableCellLimit]
   */
  dataTableCellLimit?: number;
}

/**
 * @interface
 * An interface representing PushbotsPage.
 */
export interface PushbotsPage {
  /**
   * @member {Pushbot[]} [pushbots] **NOTE: This property will not be
   * serialized. It can only be populated by the server.**
   */
  readonly pushbots?: Pushbot[];
  /**
   * @member {string} [nextPageToken]
   */
  nextPageToken?: string;
  /**
   * @member {number} [count] **NOTE: This property will not be serialized. It
   * can only be populated by the server.**
   */
  readonly count?: number;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIOptions.
 * @extends ServiceClientOptions
 */
export interface CatalyticSDKAPIOptions extends ServiceClientOptions {
  /**
   * @member {string} [baseUri]
   */
  baseUri?: string;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIFindActionsOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIFindActionsOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [query] Free text query terms to search all attributes
   * for
   */
  query?: string;
  /**
   * @member {string} [status] Run or task status to search for
   */
  status?: string;
  /**
   * @member {string} [processId] Process ID (aka Pushbot ID) to search for
   */
  processId?: string;
  /**
   * @member {string} [runId] RunID (aka Instance ID) to search for
   */
  runId?: string;
  /**
   * @member {string} [owner] Run or task owner to search for
   */
  owner?: string;
  /**
   * @member {string} [category] Category of process or run to search for
   */
  category?: string;
  /**
   * @member {string} [pageToken] The token representing the result page to get
   */
  pageToken?: string;
  /**
   * @member {number} [pageSize] The page size requested
   */
  pageSize?: number;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPICreateActionOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPICreateActionOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {RegisterActionRequest} [body] The definition of the action to
   * create
   */
  body?: RegisterActionRequest;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIUpdateActionOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIUpdateActionOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {UpdateActionRequest} [body] The updates to apply to the action
   */
  body?: UpdateActionRequest;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIFindActionWorkersOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIFindActionWorkersOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [query] Free text query terms to search all attributes
   * for
   */
  query?: string;
  /**
   * @member {string} [status] Run or task status to search for
   */
  status?: string;
  /**
   * @member {string} [processId] Process ID (aka Pushbot ID) to search for
   */
  processId?: string;
  /**
   * @member {string} [runId] RunID (aka Instance ID) to search for
   */
  runId?: string;
  /**
   * @member {string} [owner] Run or task owner to search for
   */
  owner?: string;
  /**
   * @member {string} [category] Category of process or run to search for
   */
  category?: string;
  /**
   * @member {string} [pageToken] The token representing the result page to get
   */
  pageToken?: string;
  /**
   * @member {number} [pageSize] The page size requested
   */
  pageSize?: number;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPICreateActionWorkerOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPICreateActionWorkerOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {CreateActionWorkerRequest} [body] The definition of the action
   * worker to create
   */
  body?: CreateActionWorkerRequest;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIUpdateActionWorkerOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIUpdateActionWorkerOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {UpdateActionWorkerRequest} [body] The updates to apply to the
   * action worker
   */
  body?: UpdateActionWorkerRequest;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPICreateDeveloperKeyOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPICreateDeveloperKeyOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {CreateDeveloperKeyRequest} [body] Params required to request a
   * new Developer Key
   */
  body?: CreateDeveloperKeyRequest;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIWaitForDeveloperKeyActivationOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIWaitForDeveloperKeyActivationOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {DeveloperKeyActivationRequest} [body] Params required to poll for
   * and activate Developer Key
   */
  body?: DeveloperKeyActivationRequest;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIDownloadDataTableOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIDownloadDataTableOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {Format} [format] The format to export the data table in. csv
   * (default) or excel. Possible values include: 'csv', 'excel'
   */
  format?: Format;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIUploadDataTableOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIUploadDataTableOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string[]} [files]
   */
  files?: string[];
  /**
   * @member {string} [tableName] The name of the table to create. Defaults to
   * the file name without the extension
   */
  tableName?: string;
  /**
   * @member {number} [headerRow] The row number that contains the column
   * headers. Defaults to 1. Default value: 1 .
   */
  headerRow?: number;
  /**
   * @member {number} [sheetNumber] The number of the sheet to import. Only
   * applies to Excel files. The first sheet is imported by default. Default
   * value: 1 .
   */
  sheetNumber?: number;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIFindDataTablesOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIFindDataTablesOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [query] Free text query terms to search all attributes
   * for
   */
  query?: string;
  /**
   * @member {string} [status] Run or task status to search for
   */
  status?: string;
  /**
   * @member {string} [processId] Process ID (aka Pushbot ID) to search for
   */
  processId?: string;
  /**
   * @member {string} [runId] RunID (aka Instance ID) to search for
   */
  runId?: string;
  /**
   * @member {string} [owner] Run or task owner to search for
   */
  owner?: string;
  /**
   * @member {string} [category] Category of process or run to search for
   */
  category?: string;
  /**
   * @member {string} [pageToken] The token representing the result page to get
   */
  pageToken?: string;
  /**
   * @member {number} [pageSize] The page size requested
   */
  pageSize?: number;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIFindDeveloperKeysOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIFindDeveloperKeysOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [pageToken] The token representing the result page to get
   */
  pageToken?: string;
  /**
   * @member {number} [pageSize] The page size requested
   */
  pageSize?: number;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIUploadFilesOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIUploadFilesOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string[]} [files]
   */
  files?: string[];
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIFindFilesOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIFindFilesOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [query] Free text query terms to search all attributes
   * for
   */
  query?: string;
  /**
   * @member {string} [status] Run or task status to search for
   */
  status?: string;
  /**
   * @member {string} [processId] Process ID (aka Pushbot ID) to search for
   */
  processId?: string;
  /**
   * @member {string} [runId] RunID (aka Instance ID) to search for
   */
  runId?: string;
  /**
   * @member {string} [owner] Run or task owner to search for
   */
  owner?: string;
  /**
   * @member {string} [category] Category of process or run to search for
   */
  category?: string;
  /**
   * @member {string} [pageToken] The token representing the result page to get
   */
  pageToken?: string;
  /**
   * @member {number} [pageSize] The page size requested
   */
  pageSize?: number;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIFindInstancesOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIFindInstancesOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [query] Free text query terms to search all attributes
   * for
   */
  query?: string;
  /**
   * @member {string} [status] Run or task status to search for
   */
  status?: string;
  /**
   * @member {string} [processId] Process ID (aka Pushbot ID) to search for
   */
  processId?: string;
  /**
   * @member {string} [runId] RunID (aka Instance ID) to search for
   */
  runId?: string;
  /**
   * @member {string} [owner] Run or task owner to search for
   */
  owner?: string;
  /**
   * @member {string} [category] Category of process or run to search for
   */
  category?: string;
  /**
   * @member {string} [pageToken] The token representing the result page to get
   */
  pageToken?: string;
  /**
   * @member {number} [pageSize] The page size requested
   */
  pageSize?: number;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIStartInstanceOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIStartInstanceOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {StartInstanceRequest} [body] The details of the Instance to start
   */
  body?: StartInstanceRequest;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIFindInstanceStepsOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIFindInstanceStepsOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [query] Free text query terms to search all attributes
   * for
   */
  query?: string;
  /**
   * @member {string} [status] Run or task status to search for
   */
  status?: string;
  /**
   * @member {string} [processId] Process ID (aka Pushbot ID) to search for
   */
  processId?: string;
  /**
   * @member {string} [runId] RunID (aka Instance ID) to search for
   */
  runId?: string;
  /**
   * @member {string} [owner] Run or task owner to search for
   */
  owner?: string;
  /**
   * @member {string} [category] Category of process or run to search for
   */
  category?: string;
  /**
   * @member {string} [pageToken] The token representing the result page to get
   */
  pageToken?: string;
  /**
   * @member {number} [pageSize] The page size requested
   */
  pageSize?: number;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPICompleteStepOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPICompleteStepOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {CompleteStepRequest} [body] The values of the fields to complete
   * the task with
   */
  body?: CompleteStepRequest;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIReassignStepOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIReassignStepOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {ReassignTaskRequest} [body] Contains the email address of the
   * user to reassign the Instance Step to
   */
  body?: ReassignTaskRequest;
}

/**
 * @interface
 * An interface representing CatalyticSDKAPIFindPushbotsOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CatalyticSDKAPIFindPushbotsOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [query] Free text query terms to search all attributes
   * for
   */
  query?: string;
  /**
   * @member {string} [status] Run or task status to search for
   */
  status?: string;
  /**
   * @member {string} [processId] Process ID (aka Pushbot ID) to search for
   */
  processId?: string;
  /**
   * @member {string} [runId] RunID (aka Instance ID) to search for
   */
  runId?: string;
  /**
   * @member {string} [owner] Run or task owner to search for
   */
  owner?: string;
  /**
   * @member {string} [category] Category of process or run to search for
   */
  category?: string;
  /**
   * @member {string} [pageToken] The token representing the result page to get
   */
  pageToken?: string;
  /**
   * @member {number} [pageSize] The page size requested
   */
  pageSize?: number;
}

/**
 * Defines values for Type.
 * Possible values include: 'undefined', 'text', 'integer', 'decimal', 'date', 'dateTime',
 * 'boolean', 'singleChoice', 'multipleChoice', 'json', 'file', 'table', 'pushbot', 'instance',
 * 'user'
 * @readonly
 * @enum {string}
 */
export type Type = 'undefined' | 'text' | 'integer' | 'decimal' | 'date' | 'dateTime' | 'boolean' | 'singleChoice' | 'multipleChoice' | 'json' | 'file' | 'table' | 'pushbot' | 'instance' | 'user';

/**
 * Defines values for Type1.
 * Possible values include: 'undefined', 'text', 'integer', 'decimal', 'date', 'dateTime',
 * 'boolean', 'singleChoice', 'multipleChoice', 'json', 'file', 'table', 'pushbot', 'instance',
 * 'user'
 * @readonly
 * @enum {string}
 */
export type Type1 = 'undefined' | 'text' | 'integer' | 'decimal' | 'date' | 'dateTime' | 'boolean' | 'singleChoice' | 'multipleChoice' | 'json' | 'file' | 'table' | 'pushbot' | 'instance' | 'user';

/**
 * Defines values for Status.
 * Possible values include: 'requested', 'approved', 'active', 'revoked'
 * @readonly
 * @enum {string}
 */
export type Status = 'requested' | 'approved' | 'active' | 'revoked';

/**
 * Defines values for Type2.
 * Possible values include: 'undefined', 'text', 'integer', 'decimal', 'date', 'dateTime', 'json',
 * 'bool', 'singleChoice', 'multipleChoice', 'instructions', 'file', 'table', 'pushbot',
 * 'instance', 'user'
 * @readonly
 * @enum {string}
 */
export type Type2 = 'undefined' | 'text' | 'integer' | 'decimal' | 'date' | 'dateTime' | 'json' | 'bool' | 'singleChoice' | 'multipleChoice' | 'instructions' | 'file' | 'table' | 'pushbot' | 'instance' | 'user';

/**
 * Defines values for Type3.
 * Possible values include: 'imported', 'master', 'application', 'instance', 'batch'
 * @readonly
 * @enum {string}
 */
export type Type3 = 'imported' | 'master' | 'application' | 'instance' | 'batch';

/**
 * Defines values for Visibility.
 * Possible values include: 'open', 'restricted'
 * @readonly
 * @enum {string}
 */
export type Visibility = 'open' | 'restricted';

/**
 * Defines values for Status1.
 * Possible values include: 'pending', 'active', 'completed', 'cancelled', 'snoozed', 'skipped',
 * 'error'
 * @readonly
 * @enum {string}
 */
export type Status1 = 'pending' | 'active' | 'completed' | 'cancelled' | 'snoozed' | 'skipped' | 'error';

/**
 * Defines values for FieldType.
 * Possible values include: 'undefined', 'text', 'integer', 'decimal', 'date', 'dateTime', 'json',
 * 'bool', 'singleChoice', 'multipleChoice', 'instructions', 'file', 'table', 'pushbot',
 * 'instance', 'user'
 * @readonly
 * @enum {string}
 */
export type FieldType = 'undefined' | 'text' | 'integer' | 'decimal' | 'date' | 'dateTime' | 'json' | 'bool' | 'singleChoice' | 'multipleChoice' | 'instructions' | 'file' | 'table' | 'pushbot' | 'instance' | 'user';

/**
 * Defines values for Status2.
 * Possible values include: 'running', 'completed', 'cancelled'
 * @readonly
 * @enum {string}
 */
export type Status2 = 'running' | 'completed' | 'cancelled';

/**
 * Defines values for FieldVisibility.
 * Possible values include: 'public', 'internal', 'confidential', 'highlyConfidential'
 * @readonly
 * @enum {string}
 */
export type FieldVisibility = 'public' | 'internal' | 'confidential' | 'highlyConfidential';

/**
 * Defines values for Visibility1.
 * Possible values include: 'open', 'restricted'
 * @readonly
 * @enum {string}
 */
export type Visibility1 = 'open' | 'restricted';

/**
 * Defines values for FieldVisibility1.
 * Possible values include: 'public', 'internal', 'confidential', 'highlyConfidential'
 * @readonly
 * @enum {string}
 */
export type FieldVisibility1 = 'public' | 'internal' | 'confidential' | 'highlyConfidential';

/**
 * Defines values for InstanceVisibility.
 * Possible values include: 'open', 'restricted'
 * @readonly
 * @enum {string}
 */
export type InstanceVisibility = 'open' | 'restricted';

/**
 * Defines values for Format.
 * Possible values include: 'csv', 'excel'
 * @readonly
 * @enum {string}
 */
export type Format = 'csv' | 'excel';

/**
 * Contains response data for the findActions operation.
 */
export type FindActionsResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the createAction operation.
 */
export type CreateActionResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getAction operation.
 */
export type GetActionResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the deleteAction operation.
 */
export type DeleteActionResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the updateAction operation.
 */
export type UpdateActionResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the findActionWorkers operation.
 */
export type FindActionWorkersResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the createActionWorker operation.
 */
export type CreateActionWorkerResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getActionWorker operation.
 */
export type GetActionWorkerResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the deleteActionWorker operation.
 */
export type DeleteActionWorkerResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the updateActionWorker operation.
 */
export type UpdateActionWorkerResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the createDeveloperKey operation.
 */
export type CreateDeveloperKeyResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the waitForDeveloperKeyActivation operation.
 */
export type WaitForDeveloperKeyActivationResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getDataTable operation.
 */
export type GetDataTableResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the downloadDataTable operation.
 */
export type DownloadDataTableResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the uploadDataTable operation.
 */
export type UploadDataTableResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the findDataTables operation.
 */
export type FindDataTablesResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the findDeveloperKeys operation.
 */
export type FindDeveloperKeysResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the revokeDeveloperKey operation.
 */
export type RevokeDeveloperKeyResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getFile operation.
 */
export type GetFileResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the downloadFile operation.
 */
export type DownloadFileResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the uploadFiles operation.
 */
export type UploadFilesResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the findFiles operation.
 */
export type FindFilesResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the findInstances operation.
 */
export type FindInstancesResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the startInstance operation.
 */
export type StartInstanceResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getInstance operation.
 */
export type GetInstanceResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the stopInstance operation.
 */
export type StopInstanceResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the findInstanceSteps operation.
 */
export type FindInstanceStepsResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getInstanceStep operation.
 */
export type GetInstanceStepResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the completeStep operation.
 */
export type CompleteStepResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the startStep operation.
 */
export type StartStepResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the snoozeStep operation.
 */
export type SnoozeStepResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the reassignStep operation.
 */
export type ReassignStepResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the findPushbots operation.
 */
export type FindPushbotsResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getPushbot operation.
 */
export type GetPushbotResponse = {
  /**
   * The parsed response body.
   */
  body: any;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};
