/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";


export const ProblemDetails: msRest.CompositeMapper = {
  serializedName: "ProblemDetails",
  type: {
    name: "Composite",
    className: "ProblemDetails",
    modelProperties: {
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      title: {
        serializedName: "title",
        type: {
          name: "String"
        }
      },
      status: {
        nullable: true,
        serializedName: "status",
        type: {
          name: "Number"
        }
      },
      detail: {
        serializedName: "detail",
        type: {
          name: "String"
        }
      },
      instance: {
        serializedName: "instance",
        type: {
          name: "String"
        }
      },
      extensions: {
        serializedName: "extensions",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "Object"
            }
          }
        }
      }
    }
  }
};

export const AccessToken: msRest.CompositeMapper = {
  serializedName: "AccessToken",
  type: {
    name: "Composite",
    className: "AccessToken",
    modelProperties: {
      id: {
        required: true,
        serializedName: "id",
        type: {
          name: "Uuid"
        }
      },
      domain: {
        required: true,
        serializedName: "domain",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      token: {
        serializedName: "token",
        type: {
          name: "String"
        }
      },
      secret: {
        serializedName: "secret",
        type: {
          name: "String"
        }
      },
      environment: {
        serializedName: "environment",
        type: {
          name: "String"
        }
      },
      owner: {
        serializedName: "owner",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const PagingOptions: msRest.CompositeMapper = {
  serializedName: "PagingOptions",
  type: {
    name: "Composite",
    className: "PagingOptions",
    modelProperties: {
      size: {
        serializedName: "size",
        type: {
          name: "Number"
        }
      },
      pageToken: {
        serializedName: "pageToken",
        type: {
          name: "String"
        }
      },
      getAllResults: {
        serializedName: "getAllResults",
        type: {
          name: "Boolean"
        }
      }
    }
  }
};

export const AccessTokensPage: msRest.CompositeMapper = {
  serializedName: "AccessTokensPage",
  type: {
    name: "Composite",
    className: "AccessTokensPage",
    modelProperties: {
      accessTokens: {
        serializedName: "accessTokens",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "AccessToken"
            }
          }
        }
      },
      nextPageOptions: {
        serializedName: "nextPageOptions",
        type: {
          name: "Composite",
          className: "PagingOptions"
        }
      },
      nextPageToken: {
        serializedName: "nextPageToken",
        type: {
          name: "String"
        }
      },
      count: {
        serializedName: "count",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const AccessTokenCreationRequest: msRest.CompositeMapper = {
  serializedName: "AccessTokenCreationRequest",
  type: {
    name: "Composite",
    className: "AccessTokenCreationRequest",
    modelProperties: {
      domain: {
        required: true,
        serializedName: "domain",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const AccessTokenCreationWithEmailAndPasswordRequest: msRest.CompositeMapper = {
  serializedName: "AccessTokenCreationWithEmailAndPasswordRequest",
  type: {
    name: "Composite",
    className: "AccessTokenCreationWithEmailAndPasswordRequest",
    modelProperties: {
      email: {
        required: true,
        serializedName: "email",
        type: {
          name: "String"
        }
      },
      password: {
        required: true,
        serializedName: "password",
        type: {
          name: "String"
        }
      },
      domain: {
        required: true,
        serializedName: "domain",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const WaitForAccessTokenApprovalRequest: msRest.CompositeMapper = {
  serializedName: "WaitForAccessTokenApprovalRequest",
  type: {
    name: "Composite",
    className: "WaitForAccessTokenApprovalRequest",
    modelProperties: {
      token: {
        required: true,
        serializedName: "token",
        type: {
          name: "String"
        }
      },
      waitTimeMillis: {
        nullable: true,
        serializedName: "waitTimeMillis",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const FieldRestrictions: msRest.CompositeMapper = {
  serializedName: "FieldRestrictions",
  type: {
    name: "Composite",
    className: "FieldRestrictions",
    modelProperties: {
      choices: {
        serializedName: "choices",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      valueRequired: {
        serializedName: "valueRequired",
        type: {
          name: "Boolean"
        }
      }
    }
  }
};

export const DataTableColumn: msRest.CompositeMapper = {
  serializedName: "DataTableColumn",
  type: {
    name: "Composite",
    className: "DataTableColumn",
    modelProperties: {
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      referenceName: {
        serializedName: "referenceName",
        type: {
          name: "String"
        }
      },
      restrictions: {
        serializedName: "restrictions",
        type: {
          name: "Composite",
          className: "FieldRestrictions"
        }
      }
    }
  }
};

export const DataTable: msRest.CompositeMapper = {
  serializedName: "DataTable",
  type: {
    name: "Composite",
    className: "DataTable",
    modelProperties: {
      id: {
        required: true,
        serializedName: "id",
        type: {
          name: "Uuid"
        }
      },
      dataTableId: {
        serializedName: "dataTableId",
        type: {
          name: "Uuid"
        }
      },
      referenceName: {
        serializedName: "referenceName",
        type: {
          name: "String"
        }
      },
      name: {
        required: true,
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      teamName: {
        required: true,
        serializedName: "teamName",
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      columns: {
        serializedName: "columns",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "DataTableColumn"
            }
          }
        }
      },
      isArchived: {
        serializedName: "isArchived",
        type: {
          name: "Boolean"
        }
      },
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      visibility: {
        serializedName: "visibility",
        type: {
          name: "String"
        }
      },
      visibleToUsers: {
        serializedName: "visibleToUsers",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      rowLimit: {
        serializedName: "rowLimit",
        type: {
          name: "Number"
        }
      },
      columnLimit: {
        serializedName: "columnLimit",
        type: {
          name: "Number"
        }
      },
      cellLimit: {
        serializedName: "cellLimit",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const DataTablesPage: msRest.CompositeMapper = {
  serializedName: "DataTablesPage",
  type: {
    name: "Composite",
    className: "DataTablesPage",
    modelProperties: {
      dataTables: {
        serializedName: "dataTables",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "DataTable"
            }
          }
        }
      },
      nextPageOptions: {
        serializedName: "nextPageOptions",
        type: {
          name: "Composite",
          className: "PagingOptions"
        }
      },
      nextPageToken: {
        serializedName: "nextPageToken",
        type: {
          name: "String"
        }
      },
      count: {
        serializedName: "count",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const FileMetadata: msRest.CompositeMapper = {
  serializedName: "FileMetadata",
  type: {
    name: "Composite",
    className: "FileMetadata",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "Uuid"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      teamName: {
        serializedName: "teamName",
        type: {
          name: "String"
        }
      },
      contentType: {
        serializedName: "contentType",
        type: {
          name: "String"
        }
      },
      sizeInBytes: {
        serializedName: "sizeInBytes",
        type: {
          name: "Number"
        }
      },
      displaySize: {
        serializedName: "displaySize",
        type: {
          name: "String"
        }
      },
      isPublic: {
        serializedName: "isPublic",
        type: {
          name: "Boolean"
        }
      },
      md5Hash: {
        serializedName: "md5Hash",
        type: {
          name: "String"
        }
      },
      referenceName: {
        serializedName: "referenceName",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const FileMetadataPage: msRest.CompositeMapper = {
  serializedName: "FileMetadataPage",
  type: {
    name: "Composite",
    className: "FileMetadataPage",
    modelProperties: {
      files: {
        serializedName: "files",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "FileMetadata"
            }
          }
        }
      },
      nextPageOptions: {
        serializedName: "nextPageOptions",
        type: {
          name: "Composite",
          className: "PagingOptions"
        }
      },
      nextPageToken: {
        serializedName: "nextPageToken",
        type: {
          name: "String"
        }
      },
      count: {
        serializedName: "count",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const Field: msRest.CompositeMapper = {
  serializedName: "Field",
  type: {
    name: "Composite",
    className: "Field",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "Uuid"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      referenceName: {
        serializedName: "referenceName",
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      example: {
        serializedName: "example",
        type: {
          name: "String"
        }
      },
      position: {
        serializedName: "position",
        type: {
          name: "Number"
        }
      },
      restrictions: {
        serializedName: "restrictions",
        type: {
          name: "Composite",
          className: "FieldRestrictions"
        }
      },
      fieldType: {
        serializedName: "fieldType",
        type: {
          name: "String"
        }
      },
      value: {
        serializedName: "value",
        type: {
          name: "String"
        }
      },
      templateValue: {
        serializedName: "templateValue",
        type: {
          name: "String"
        }
      },
      defaultValue: {
        serializedName: "defaultValue",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const InstanceStep: msRest.CompositeMapper = {
  serializedName: "InstanceStep",
  type: {
    name: "Composite",
    className: "InstanceStep",
    modelProperties: {
      id: {
        required: true,
        serializedName: "id",
        type: {
          name: "Uuid"
        }
      },
      instanceId: {
        required: true,
        serializedName: "instanceId",
        type: {
          name: "Uuid"
        }
      },
      workflowId: {
        required: true,
        serializedName: "workflowId",
        type: {
          name: "Uuid"
        }
      },
      name: {
        required: true,
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      teamName: {
        required: true,
        serializedName: "teamName",
        type: {
          name: "String"
        }
      },
      position: {
        serializedName: "position",
        type: {
          name: "Number"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      status: {
        serializedName: "status",
        type: {
          name: "String"
        }
      },
      assignedTo: {
        serializedName: "assignedTo",
        type: {
          name: "String"
        }
      },
      actionTypeId: {
        serializedName: "actionTypeId",
        type: {
          name: "String"
        }
      },
      isAutomated: {
        serializedName: "isAutomated",
        type: {
          name: "Boolean"
        }
      },
      isManual: {
        serializedName: "isManual",
        type: {
          name: "Boolean"
        }
      },
      startDate: {
        serializedName: "startDate",
        type: {
          name: "DateTime"
        }
      },
      endDate: {
        serializedName: "endDate",
        type: {
          name: "DateTime"
        }
      },
      outputFields: {
        serializedName: "outputFields",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Field"
            }
          }
        }
      }
    }
  }
};

export const Instance: msRest.CompositeMapper = {
  serializedName: "Instance",
  type: {
    name: "Composite",
    className: "Instance",
    modelProperties: {
      id: {
        required: true,
        serializedName: "id",
        type: {
          name: "Uuid"
        }
      },
      workflowId: {
        required: true,
        serializedName: "workflowId",
        type: {
          name: "Uuid"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      teamName: {
        required: true,
        serializedName: "teamName",
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      category: {
        serializedName: "category",
        type: {
          name: "String"
        }
      },
      owner: {
        serializedName: "owner",
        type: {
          name: "String"
        }
      },
      createdBy: {
        serializedName: "createdBy",
        type: {
          name: "String"
        }
      },
      steps: {
        serializedName: "steps",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "InstanceStep"
            }
          }
        }
      },
      fields: {
        serializedName: "fields",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Field"
            }
          }
        }
      },
      status: {
        serializedName: "status",
        type: {
          name: "String"
        }
      },
      startDate: {
        serializedName: "startDate",
        type: {
          name: "DateTime"
        }
      },
      endDate: {
        serializedName: "endDate",
        type: {
          name: "DateTime"
        }
      },
      fieldVisibility: {
        serializedName: "fieldVisibility",
        type: {
          name: "String"
        }
      },
      visibility: {
        serializedName: "visibility",
        type: {
          name: "String"
        }
      },
      visibleToUsers: {
        serializedName: "visibleToUsers",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const InstancesPage: msRest.CompositeMapper = {
  serializedName: "InstancesPage",
  type: {
    name: "Composite",
    className: "InstancesPage",
    modelProperties: {
      instances: {
        serializedName: "instances",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Instance"
            }
          }
        }
      },
      nextPageOptions: {
        serializedName: "nextPageOptions",
        type: {
          name: "Composite",
          className: "PagingOptions"
        }
      },
      nextPageToken: {
        serializedName: "nextPageToken",
        type: {
          name: "String"
        }
      },
      count: {
        serializedName: "count",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const FieldUpdateRequest: msRest.CompositeMapper = {
  serializedName: "FieldUpdateRequest",
  type: {
    name: "Composite",
    className: "FieldUpdateRequest",
    modelProperties: {
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      referenceName: {
        serializedName: "referenceName",
        type: {
          name: "String"
        }
      },
      value: {
        serializedName: "value",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const StartInstanceRequest: msRest.CompositeMapper = {
  serializedName: "StartInstanceRequest",
  type: {
    name: "Composite",
    className: "StartInstanceRequest",
    modelProperties: {
      workflowId: {
        serializedName: "workflowId",
        type: {
          name: "Uuid"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      inputFields: {
        serializedName: "inputFields",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "FieldUpdateRequest"
            }
          }
        }
      }
    }
  }
};

export const InstanceStepsPage: msRest.CompositeMapper = {
  serializedName: "InstanceStepsPage",
  type: {
    name: "Composite",
    className: "InstanceStepsPage",
    modelProperties: {
      steps: {
        serializedName: "steps",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "InstanceStep"
            }
          }
        }
      },
      nextPageOptions: {
        serializedName: "nextPageOptions",
        type: {
          name: "Composite",
          className: "PagingOptions"
        }
      },
      nextPageToken: {
        serializedName: "nextPageToken",
        type: {
          name: "String"
        }
      },
      count: {
        serializedName: "count",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const CompleteStepRequest: msRest.CompositeMapper = {
  serializedName: "CompleteStepRequest",
  type: {
    name: "Composite",
    className: "CompleteStepRequest",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "Uuid"
        }
      },
      stepOutputFields: {
        serializedName: "stepOutputFields",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "FieldUpdateRequest"
            }
          }
        }
      }
    }
  }
};

export const ReassignStepRequest: msRest.CompositeMapper = {
  serializedName: "ReassignStepRequest",
  type: {
    name: "Composite",
    className: "ReassignStepRequest",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "Uuid"
        }
      },
      assignTo: {
        serializedName: "assignTo",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const IntegrationConnection: msRest.CompositeMapper = {
  serializedName: "IntegrationConnection",
  type: {
    name: "Composite",
    className: "IntegrationConnection",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      referenceName: {
        serializedName: "referenceName",
        type: {
          name: "String"
        }
      },
      integrationId: {
        serializedName: "integrationId",
        type: {
          name: "String"
        }
      },
      createdAt: {
        serializedName: "createdAt",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const Integration: msRest.CompositeMapper = {
  serializedName: "Integration",
  type: {
    name: "Composite",
    className: "Integration",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      referenceName: {
        serializedName: "referenceName",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      isCustomIntegration: {
        serializedName: "isCustomIntegration",
        type: {
          name: "Boolean"
        }
      },
      connections: {
        serializedName: "connections",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "IntegrationConnection"
            }
          }
        }
      },
      connectionParams: {
        serializedName: "connectionParams",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Field"
            }
          }
        }
      }
    }
  }
};

export const IntegrationsPage: msRest.CompositeMapper = {
  serializedName: "IntegrationsPage",
  type: {
    name: "Composite",
    className: "IntegrationsPage",
    modelProperties: {
      integrations: {
        serializedName: "integrations",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Integration"
            }
          }
        }
      },
      nextPageOptions: {
        serializedName: "nextPageOptions",
        type: {
          name: "Composite",
          className: "PagingOptions"
        }
      },
      nextPageToken: {
        serializedName: "nextPageToken",
        type: {
          name: "String"
        }
      },
      count: {
        serializedName: "count",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const IntegrationConfiguration: msRest.CompositeMapper = {
  serializedName: "IntegrationConfiguration",
  type: {
    name: "Composite",
    className: "IntegrationConfiguration",
    modelProperties: {
      clientId: {
        required: true,
        serializedName: "clientId",
        type: {
          name: "String"
        }
      },
      clientSecret: {
        required: true,
        serializedName: "clientSecret",
        type: {
          name: "String"
        }
      },
      tokenPath: {
        required: true,
        serializedName: "tokenPath",
        type: {
          name: "String"
        }
      },
      revokePath: {
        required: true,
        serializedName: "revokePath",
        type: {
          name: "String"
        }
      },
      site: {
        required: true,
        serializedName: "site",
        type: {
          name: "String"
        }
      },
      authorizeBaseUrl: {
        required: true,
        serializedName: "authorizeBaseUrl",
        type: {
          name: "String"
        }
      },
      scopes: {
        serializedName: "scopes",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      useBodyAuth: {
        nullable: true,
        serializedName: "useBodyAuth",
        type: {
          name: "Boolean"
        }
      }
    }
  }
};

export const IntegrationCreationRequest: msRest.CompositeMapper = {
  serializedName: "IntegrationCreationRequest",
  type: {
    name: "Composite",
    className: "IntegrationCreationRequest",
    modelProperties: {
      name: {
        required: true,
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      type: {
        required: true,
        isConstant: true,
        serializedName: "type",
        defaultValue: 'oAuth2',
        type: {
          name: "String"
        }
      },
      config: {
        required: true,
        serializedName: "config",
        type: {
          name: "Composite",
          className: "IntegrationConfiguration"
        }
      }
    }
  }
};

export const IntegrationUpdateRequest: msRest.CompositeMapper = {
  serializedName: "IntegrationUpdateRequest",
  type: {
    name: "Composite",
    className: "IntegrationUpdateRequest",
    modelProperties: {
      name: {
        required: true,
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      type: {
        required: true,
        isConstant: true,
        serializedName: "type",
        defaultValue: 'oAuth2',
        type: {
          name: "String"
        }
      },
      config: {
        required: true,
        serializedName: "config",
        type: {
          name: "Composite",
          className: "IntegrationConfiguration"
        }
      }
    }
  }
};

export const IntegrationConnectionCreationRequest: msRest.CompositeMapper = {
  serializedName: "IntegrationConnectionCreationRequest",
  type: {
    name: "Composite",
    className: "IntegrationConnectionCreationRequest",
    modelProperties: {
      integrationId: {
        serializedName: "integrationId",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      connectionParams: {
        serializedName: "connectionParams",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "FieldUpdateRequest"
            }
          }
        }
      }
    }
  }
};

export const User: msRest.CompositeMapper = {
  serializedName: "User",
  type: {
    name: "Composite",
    className: "User",
    modelProperties: {
      id: {
        required: true,
        serializedName: "id",
        type: {
          name: "Uuid"
        }
      },
      username: {
        serializedName: "username",
        type: {
          name: "String"
        }
      },
      email: {
        required: true,
        serializedName: "email",
        type: {
          name: "String"
        }
      },
      fullName: {
        required: true,
        serializedName: "fullName",
        type: {
          name: "String"
        }
      },
      teamName: {
        required: true,
        serializedName: "teamName",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const UsersPage: msRest.CompositeMapper = {
  serializedName: "UsersPage",
  type: {
    name: "Composite",
    className: "UsersPage",
    modelProperties: {
      users: {
        serializedName: "users",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "User"
            }
          }
        }
      },
      nextPageOptions: {
        serializedName: "nextPageOptions",
        type: {
          name: "Composite",
          className: "PagingOptions"
        }
      },
      nextPageToken: {
        serializedName: "nextPageToken",
        type: {
          name: "String"
        }
      },
      count: {
        serializedName: "count",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const GuidNullableRange: msRest.CompositeMapper = {
  serializedName: "GuidNullableRange",
  type: {
    name: "Composite",
    className: "GuidNullableRange",
    modelProperties: {
      lowerBoundInclusive: {
        serializedName: "lowerBoundInclusive",
        type: {
          name: "Uuid"
        }
      },
      upperBoundInclusive: {
        serializedName: "upperBoundInclusive",
        type: {
          name: "Uuid"
        }
      }
    }
  }
};

export const GuidSearchExpression: msRest.CompositeMapper = {
  serializedName: "GuidSearchExpression",
  type: {
    name: "Composite",
    className: "GuidSearchExpression",
    modelProperties: {
      isEqualTo: {
        serializedName: "isEqualTo",
        type: {
          name: "Uuid"
        }
      },
      between: {
        serializedName: "between",
        type: {
          name: "Composite",
          className: "GuidNullableRange"
        }
      },
      contains: {
        serializedName: "contains",
        type: {
          name: "Uuid"
        }
      }
    }
  }
};

export const StringRange: msRest.CompositeMapper = {
  serializedName: "StringRange",
  type: {
    name: "Composite",
    className: "StringRange",
    modelProperties: {
      lowerBoundInclusive: {
        serializedName: "lowerBoundInclusive",
        type: {
          name: "String"
        }
      },
      upperBoundInclusive: {
        serializedName: "upperBoundInclusive",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const StringSearchExpression: msRest.CompositeMapper = {
  serializedName: "StringSearchExpression",
  type: {
    name: "Composite",
    className: "StringSearchExpression",
    modelProperties: {
      isEqualTo: {
        serializedName: "isEqualTo",
        type: {
          name: "String"
        }
      },
      between: {
        serializedName: "between",
        type: {
          name: "Composite",
          className: "StringRange"
        }
      },
      contains: {
        serializedName: "contains",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const BooleanNullableRange: msRest.CompositeMapper = {
  serializedName: "BooleanNullableRange",
  type: {
    name: "Composite",
    className: "BooleanNullableRange",
    modelProperties: {
      lowerBoundInclusive: {
        nullable: true,
        serializedName: "lowerBoundInclusive",
        type: {
          name: "Boolean"
        }
      },
      upperBoundInclusive: {
        nullable: true,
        serializedName: "upperBoundInclusive",
        type: {
          name: "Boolean"
        }
      }
    }
  }
};

export const BoolSearchExpression: msRest.CompositeMapper = {
  serializedName: "BoolSearchExpression",
  type: {
    name: "Composite",
    className: "BoolSearchExpression",
    modelProperties: {
      isEqualTo: {
        nullable: true,
        serializedName: "isEqualTo",
        type: {
          name: "Boolean"
        }
      },
      between: {
        serializedName: "between",
        type: {
          name: "Composite",
          className: "BooleanNullableRange"
        }
      },
      contains: {
        nullable: true,
        serializedName: "contains",
        type: {
          name: "Boolean"
        }
      }
    }
  }
};

export const DateTimeOffsetNullableRange: msRest.CompositeMapper = {
  serializedName: "DateTimeOffsetNullableRange",
  type: {
    name: "Composite",
    className: "DateTimeOffsetNullableRange",
    modelProperties: {
      lowerBoundInclusive: {
        serializedName: "lowerBoundInclusive",
        type: {
          name: "DateTime"
        }
      },
      upperBoundInclusive: {
        serializedName: "upperBoundInclusive",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const DateTimeSearchExpression: msRest.CompositeMapper = {
  serializedName: "DateTimeSearchExpression",
  type: {
    name: "Composite",
    className: "DateTimeSearchExpression",
    modelProperties: {
      isEqualTo: {
        serializedName: "isEqualTo",
        type: {
          name: "DateTime"
        }
      },
      between: {
        serializedName: "between",
        type: {
          name: "Composite",
          className: "DateTimeOffsetNullableRange"
        }
      },
      contains: {
        serializedName: "contains",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const UserSearchClause: msRest.CompositeMapper = {
  serializedName: "UserSearchClause",
  type: {
    name: "Composite",
    className: "UserSearchClause",
    modelProperties: {
      and: {
        serializedName: "and",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "UserSearchClause"
            }
          }
        }
      },
      or: {
        serializedName: "or",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "UserSearchClause"
            }
          }
        }
      },
      id: {
        serializedName: "id",
        type: {
          name: "Composite",
          className: "GuidSearchExpression"
        }
      },
      email: {
        serializedName: "email",
        type: {
          name: "Composite",
          className: "StringSearchExpression"
        }
      },
      fullName: {
        serializedName: "fullName",
        type: {
          name: "Composite",
          className: "StringSearchExpression"
        }
      },
      isTeamAdmin: {
        serializedName: "isTeamAdmin",
        type: {
          name: "Composite",
          className: "BoolSearchExpression"
        }
      },
      isDeactivated: {
        serializedName: "isDeactivated",
        type: {
          name: "Composite",
          className: "BoolSearchExpression"
        }
      },
      isLockedOut: {
        serializedName: "isLockedOut",
        type: {
          name: "Composite",
          className: "BoolSearchExpression"
        }
      },
      createdDate: {
        serializedName: "createdDate",
        type: {
          name: "Composite",
          className: "DateTimeSearchExpression"
        }
      }
    }
  }
};

export const Workflow: msRest.CompositeMapper = {
  serializedName: "Workflow",
  type: {
    name: "Composite",
    className: "Workflow",
    modelProperties: {
      id: {
        required: true,
        serializedName: "id",
        type: {
          name: "Uuid"
        }
      },
      name: {
        required: true,
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      teamName: {
        required: true,
        serializedName: "teamName",
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      category: {
        serializedName: "category",
        type: {
          name: "String"
        }
      },
      owner: {
        serializedName: "owner",
        type: {
          name: "String"
        }
      },
      createdBy: {
        serializedName: "createdBy",
        type: {
          name: "String"
        }
      },
      inputFields: {
        serializedName: "inputFields",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Field"
            }
          }
        }
      },
      isPublished: {
        serializedName: "isPublished",
        type: {
          name: "Boolean"
        }
      },
      isArchived: {
        serializedName: "isArchived",
        type: {
          name: "Boolean"
        }
      },
      fieldVisibility: {
        serializedName: "fieldVisibility",
        type: {
          name: "String"
        }
      },
      instanceVisibility: {
        serializedName: "instanceVisibility",
        type: {
          name: "String"
        }
      },
      adminUsers: {
        serializedName: "adminUsers",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      standardUsers: {
        serializedName: "standardUsers",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      taskCountLimit: {
        serializedName: "taskCountLimit",
        type: {
          name: "Number"
        }
      },
      fieldCountLimit: {
        serializedName: "fieldCountLimit",
        type: {
          name: "Number"
        }
      },
      fieldSizeLimit: {
        serializedName: "fieldSizeLimit",
        type: {
          name: "Number"
        }
      },
      fieldTotalSizeLimit: {
        serializedName: "fieldTotalSizeLimit",
        type: {
          name: "Number"
        }
      },
      dataTableRowLimit: {
        serializedName: "dataTableRowLimit",
        type: {
          name: "Number"
        }
      },
      dataTableColumnLimit: {
        serializedName: "dataTableColumnLimit",
        type: {
          name: "Number"
        }
      },
      dataTableCellLimit: {
        serializedName: "dataTableCellLimit",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const WorkflowsPage: msRest.CompositeMapper = {
  serializedName: "WorkflowsPage",
  type: {
    name: "Composite",
    className: "WorkflowsPage",
    modelProperties: {
      workflows: {
        serializedName: "workflows",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Workflow"
            }
          }
        }
      },
      nextPageOptions: {
        serializedName: "nextPageOptions",
        type: {
          name: "Composite",
          className: "PagingOptions"
        }
      },
      nextPageToken: {
        serializedName: "nextPageToken",
        type: {
          name: "String"
        }
      },
      count: {
        serializedName: "count",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const WorkflowSearchClause: msRest.CompositeMapper = {
  serializedName: "WorkflowSearchClause",
  type: {
    name: "Composite",
    className: "WorkflowSearchClause",
    modelProperties: {
      and: {
        serializedName: "and",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "WorkflowSearchClause"
            }
          }
        }
      },
      or: {
        serializedName: "or",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "WorkflowSearchClause"
            }
          }
        }
      },
      id: {
        serializedName: "id",
        type: {
          name: "Composite",
          className: "GuidSearchExpression"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "Composite",
          className: "StringSearchExpression"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "Composite",
          className: "StringSearchExpression"
        }
      },
      owner: {
        serializedName: "owner",
        type: {
          name: "Composite",
          className: "StringSearchExpression"
        }
      },
      category: {
        serializedName: "category",
        type: {
          name: "Composite",
          className: "StringSearchExpression"
        }
      },
      createdDate: {
        serializedName: "createdDate",
        type: {
          name: "Composite",
          className: "DateTimeSearchExpression"
        }
      }
    }
  }
};

export const WorkflowImportRequest: msRest.CompositeMapper = {
  serializedName: "WorkflowImportRequest",
  type: {
    name: "Composite",
    className: "WorkflowImportRequest",
    modelProperties: {
      fileId: {
        serializedName: "fileId",
        type: {
          name: "Uuid"
        }
      },
      password: {
        serializedName: "password",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const WorkflowImport: msRest.CompositeMapper = {
  serializedName: "WorkflowImport",
  type: {
    name: "Composite",
    className: "WorkflowImport",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "Uuid"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      workflowId: {
        serializedName: "workflowId",
        type: {
          name: "Uuid"
        }
      },
      errorMessage: {
        serializedName: "errorMessage",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const WorkflowExportRequest: msRest.CompositeMapper = {
  serializedName: "WorkflowExportRequest",
  type: {
    name: "Composite",
    className: "WorkflowExportRequest",
    modelProperties: {
      workflowId: {
        serializedName: "workflowId",
        type: {
          name: "Uuid"
        }
      },
      password: {
        serializedName: "password",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const WorkflowExport: msRest.CompositeMapper = {
  serializedName: "WorkflowExport",
  type: {
    name: "Composite",
    className: "WorkflowExport",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "Uuid"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      fileId: {
        serializedName: "fileId",
        type: {
          name: "Uuid"
        }
      },
      errorMessage: {
        serializedName: "errorMessage",
        type: {
          name: "String"
        }
      }
    }
  }
};
