/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";

export const accessIdentifier: msRest.OperationURLParameter = {
  parameterPath: "accessIdentifier",
  mapper: {
    required: true,
    serializedName: "accessIdentifier",
    type: {
      name: "String"
    }
  }
};
export const category: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "category"
  ],
  mapper: {
    serializedName: "category",
    type: {
      name: "String"
    }
  }
};
export const files: msRest.OperationParameter = {
  parameterPath: [
    "options",
    "files"
  ],
  mapper: {
    serializedName: "files",
    type: {
      name: "Sequence",
      element: {
        type: {
          name: "String"
        }
      }
    }
  }
};
export const format: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "format"
  ],
  mapper: {
    serializedName: "format",
    type: {
      name: "String"
    }
  }
};
export const headerRow: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "headerRow"
  ],
  mapper: {
    serializedName: "headerRow",
    defaultValue: 1,
    type: {
      name: "Number"
    }
  }
};
export const id: msRest.OperationURLParameter = {
  parameterPath: "id",
  mapper: {
    required: true,
    serializedName: "id",
    type: {
      name: "String"
    }
  }
};
export const instanceId: msRest.OperationURLParameter = {
  parameterPath: "instanceId",
  mapper: {
    required: true,
    serializedName: "instanceId",
    type: {
      name: "String"
    }
  }
};
export const owner: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "owner"
  ],
  mapper: {
    serializedName: "owner",
    type: {
      name: "String"
    }
  }
};
export const pageSize: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "pageSize"
  ],
  mapper: {
    serializedName: "page_size",
    type: {
      name: "Number"
    }
  }
};
export const pageToken: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "pageToken"
  ],
  mapper: {
    serializedName: "page_token",
    type: {
      name: "String"
    }
  }
};
export const processId: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "processId"
  ],
  mapper: {
    serializedName: "process_id",
    type: {
      name: "String"
    }
  }
};
export const query: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "query"
  ],
  mapper: {
    serializedName: "query",
    type: {
      name: "String"
    }
  }
};
export const runId: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "runId"
  ],
  mapper: {
    serializedName: "run_id",
    type: {
      name: "String"
    }
  }
};
export const sheetNumber: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "sheetNumber"
  ],
  mapper: {
    serializedName: "sheetNumber",
    defaultValue: 1,
    type: {
      name: "Number"
    }
  }
};
export const status: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "status"
  ],
  mapper: {
    serializedName: "status",
    type: {
      name: "String"
    }
  }
};
export const tableName: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "tableName"
  ],
  mapper: {
    serializedName: "tableName",
    type: {
      name: "String"
    }
  }
};
