# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.16.3'

    # Runs a single command using the runners shell
    - name: Install Yarn and other dependencies
      run: |
        npm i -g yarn
        yarn install

    # Runs a set of commands using the runners shell
    - name: Build, Lint, & Test
      run: |
        yarn build
        yarn lint
        yarn test

    - name: Generate code coverage
      run: yarn cover

    - name: Publish code coverage
      uses: codecov/codecov-action@v1
      with:
        file: ${{ github.workspace }}/coverage/lcov.info
